<?php
/**
 * BATANOX — admin.php  (v8 — Commercial-Grade Admin Platform)
 *
 * NEW SECTIONS:
 *   ?section=dashboard  – Overview stats, charts, top insights (default)
 *   ?section=logs       – Advanced logs: search + 5 filters + sort + export
 *   ?section=reports    – Daily & monthly report cards + export hub
 *   ?section=insights   – Real-time alerts: urgent, repeat, top users, growth
 *   ?section=users      – User management
 *
 * KEY RULES:
 *   - ONE <?php block before <!DOCTYPE — single ?> just before HTML
 *   - Every DB query wrapped in try/catch with safe fallback
 *   - safeHtml() used everywhere (never passes NULL to htmlspecialchars)
 *   - CSV export exits early before HTML output
 */

session_start();
require_once 'db_config.php';

// ── Admin guard ────────────────────────────────────────────────────────────────
$role = $_SESSION['role'] ?? $_SESSION['user_role'] ?? '';
if (!isset($_SESSION['user_id']) || $role !== 'admin') {
    header('Location: login.php');
    exit;
}
$admin_name = $_SESSION['user_name'] ?? $_SESSION['name'] ?? 'Admin';

// ── Utility helpers ────────────────────────────────────────────────────────────
function safeHtml(?string $v): string {
    return htmlspecialchars((string)($v ?? ''), ENT_QUOTES, 'UTF-8');
}
function statusLabel(string $s): string {
    return match($s) {
        'in_progress' => 'In Progress',
        'recovered'   => 'Recovered',
        default       => 'Detected',
    };
}
function statusBadgeStyle(string $s): string {
    return match($s) {
        'in_progress' => 'background:#dbeafe;color:#1e40af;border:1px solid #bfdbfe',
        'recovered'   => 'background:#dcfce7;color:#166534;border:1px solid #bbf7d0',
        default       => 'background:#fee2e2;color:#991b1b;border:1px solid #fecaca',
    };
}
function statusDotColor(string $s): string {
    return match($s) { 'in_progress' => '#3b82f6', 'recovered' => '#22c55e', default => '#ef4444' };
}
function csvCell(?string $v): string {
    $v = (string)($v ?? '');
    return (str_contains($v, ',') || str_contains($v, '"') || str_contains($v, "\n"))
        ? '"' . str_replace('"', '""', $v) . '"' : $v;
}

// ── Detect which columns exist ─────────────────────────────────────────────────
try { $ecols = $pdo->query("SHOW COLUMNS FROM disease_records")->fetchAll(PDO::FETCH_COLUMN); }
catch (PDOException $e) { $ecols = []; }
$has      = array_flip($ecols);
$has_stat = isset($has['status']);
$has_plant = isset($has['plant_name']);
$has_conf  = isset($has['confidence']);
$has_days  = isset($has['estimated_days']);
$has_treat = isset($has['treatment']);
$has_next  = isset($has['next_reminder']);

// ── Active section ─────────────────────────────────────────────────────────────
$sec = $_GET['section'] ?? 'dashboard';

// ── DELETE / CLEAR actions ─────────────────────────────────────────────────────
if (isset($_GET['del'])) {
    try { $pdo->prepare("DELETE FROM disease_records WHERE id=?")->execute([(int)$_GET['del']]); }
    catch (PDOException $e) {}
    header("Location: admin.php?section=logs&flash=deleted"); exit;
}
if (isset($_GET['clr'])) {
    try { $pdo->prepare("DELETE FROM disease_records WHERE user_id=?")->execute([(int)$_GET['clr']]); }
    catch (PDOException $e) {}
    header("Location: admin.php?section=users&flash=cleared"); exit;
}

// ── CSV EXPORT (early exit before any HTML) ───────────────────────────────────
if (isset($_GET['export']) && $_GET['export'] === 'csv') {
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="BATANOX_Report_' . date('Y-m-d_His') . '.csv"');
    // BOM for Excel UTF-8
    echo "\xEF\xBB\xBF";
    echo "BATANOX - Agricultural Disease Detection Report\r\n";
    echo "System:,BATANOX Plant Disease Detection Platform\r\n";
    echo "Generated:," . csvCell(date('Y-m-d H:i:s')) . "\r\n";
    echo "Generated By:," . csvCell($admin_name) . "\r\n\r\n";
    echo "ID,User Name,User Email,Plant,Disease Detected,Confidence %,Status,Detection Date & Time,Est. Recovery Days\r\n";
    $pc = $has_plant ? 'dr.plant_name' : "'' AS plant_name";
    $cc = $has_conf  ? 'dr.confidence' : "0 AS confidence";
    $sc = $has_stat  ? 'dr.status'     : "'detected' AS status";
    $dc = $has_days  ? 'dr.estimated_days' : "NULL AS estimated_days";
    try {
        $rows = $pdo->query("SELECT dr.id,u.name AS un,u.email AS ue,$pc,dr.disease_name,$cc,$sc,dr.scanned_at,$dc
            FROM disease_records dr JOIN users u ON dr.user_id=u.id ORDER BY dr.scanned_at DESC LIMIT 100000")->fetchAll(PDO::FETCH_ASSOC);
        foreach ($rows as $xr) {
            echo implode(',', [
                csvCell((string)$xr['id']),
                csvCell($xr['un']),
                csvCell($xr['ue']),
                csvCell($xr['plant_name'] ?? ''),
                csvCell($xr['disease_name']),
                csvCell($xr['confidence'] > 0 ? (string)$xr['confidence'] : ''),
                csvCell(statusLabel($xr['status'] ?? 'detected')),
                csvCell($xr['scanned_at']),
                csvCell((string)($xr['estimated_days'] ?? '')),
            ]) . "\r\n";
        }
    } catch (PDOException $e) {
        echo "ERROR:," . csvCell($e->getMessage()) . "\r\n";
    }
    exit;
}

// ── PER-USER CSV EXPORT (early exit) ─────────────────────────────────────────
if (isset($_GET['export']) && $_GET['export'] === 'user_csv' && isset($_GET['uid'])) {
    $exp_uid = (int)$_GET['uid'];
    // Fetch the user's name for filename
    $exp_uname = 'User';
    try {
        $r = $pdo->prepare("SELECT name FROM users WHERE id=? LIMIT 1");
        $r->execute([$exp_uid]); $ru = $r->fetch(PDO::FETCH_ASSOC);
        if ($ru) $exp_uname = preg_replace('/[^A-Za-z0-9_\-]/', '_', $ru['name']);
    } catch (PDOException $e) {}

    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="BATANOX_User_' . $exp_uname . '_' . date('Y-m-d') . '.csv"');
    echo "\xEF\xBB\xBF";
    echo "BATANOX - Individual User Disease Report\r\n";
    echo "User:," . csvCell($exp_uname) . "\r\n";
    echo "Generated:," . csvCell(date('Y-m-d H:i:s')) . "\r\n";
    echo "Generated By:," . csvCell($admin_name) . "\r\n\r\n";
    echo "ID,Plant,Disease Detected,Confidence %,Status,Treatment,Detection Date,Est. Recovery Days\r\n";
    $pc2 = $has_plant ? 'dr.plant_name' : "'' AS plant_name";
    $cc2 = $has_conf  ? 'dr.confidence' : "0 AS confidence";
    $sc2 = $has_stat  ? 'dr.status'     : "'detected' AS status";
    $dc2 = $has_days  ? 'dr.estimated_days' : "NULL AS estimated_days";
    $tc2 = $has_treat ? 'dr.treatment'  : "'' AS treatment";
    try {
        $stmt2 = $pdo->prepare("SELECT dr.id,$pc2,dr.disease_name,$cc2,$sc2,$tc2,dr.scanned_at,$dc2
            FROM disease_records dr WHERE dr.user_id=? ORDER BY dr.scanned_at DESC");
        $stmt2->execute([$exp_uid]);
        $rows2 = $stmt2->fetchAll(PDO::FETCH_ASSOC);
        foreach ($rows2 as $xr2) {
            echo implode(',', [
                csvCell((string)$xr2['id']),
                csvCell($xr2['plant_name'] ?? ''),
                csvCell($xr2['disease_name']),
                csvCell($xr2['confidence'] > 0 ? (string)$xr2['confidence'] : ''),
                csvCell(statusLabel($xr2['status'] ?? 'detected')),
                csvCell($xr2['treatment'] ?? ''),
                csvCell($xr2['scanned_at']),
                csvCell((string)($xr2['estimated_days'] ?? '')),
            ]) . "\r\n";
        }
    } catch (PDOException $e) {
        echo "ERROR:," . csvCell($e->getMessage()) . "\r\n";
    }
    exit;
}

// ══════════════════════════════════════════════════════════════════════════════
//  CORE STATISTICS  (always needed for sidebar counters and dashboard)
// ══════════════════════════════════════════════════════════════════════════════
$ttl_users = 0;
try { $ttl_users = (int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='user'")->fetchColumn(); } catch (PDOException $e) {}

$ttl_recs = 0;
try { $ttl_recs = (int)$pdo->query("SELECT COUNT(*) FROM disease_records")->fetchColumn(); } catch (PDOException $e) {}

$ttl_recovered = 0;
if ($has_stat) { try { $ttl_recovered = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE status='recovered'")->fetchColumn(); } catch (PDOException $e) {} }

$ttl_active = 0;
if ($has_stat) { try { $ttl_active = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE status='in_progress'")->fetchColumn(); } catch (PDOException $e) {} }

$rec_rate = $ttl_recs > 0 ? (int)round(($ttl_recovered / $ttl_recs) * 100) : 0;

// 30-day growth %
$growth_pct = 0; $growth_dir = 'up';
try {
    $recent30 = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE scanned_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)")->fetchColumn();
    $prior30  = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE scanned_at >= DATE_SUB(NOW(), INTERVAL 60 DAY) AND scanned_at < DATE_SUB(NOW(), INTERVAL 30 DAY)")->fetchColumn();
    if ($prior30 > 0) { $growth_pct = (int)round((($recent30 - $prior30) / $prior30) * 100); }
    elseif ($recent30 > 0) { $growth_pct = 100; }
    $growth_dir = $growth_pct >= 0 ? 'up' : 'dn';
} catch (PDOException $e) {}

// Top disease / top plant
$top_dis_name = 'N/A'; $top_dis_cnt = 0;
try {
    $r = $pdo->query("SELECT disease_name,COUNT(*) c FROM disease_records WHERE disease_name IS NOT NULL AND TRIM(disease_name)!='' GROUP BY disease_name ORDER BY c DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);
    if ($r) { $top_dis_name = $r['disease_name']; $top_dis_cnt = (int)$r['c']; }
} catch (PDOException $e) {}

$top_plant_name = 'N/A'; $top_plant_cnt = 0;
if ($has_plant) {
    try {
        $r = $pdo->query("SELECT plant_name,COUNT(*) c FROM disease_records WHERE plant_name IS NOT NULL AND TRIM(plant_name)!='' GROUP BY plant_name ORDER BY c DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);
        if ($r) { $top_plant_name = $r['plant_name']; $top_plant_cnt = (int)$r['c']; }
    } catch (PDOException $e) {}
}

// Disease breakdown top 6
$dis_breakdown = [];
try {
    $dis_breakdown = $pdo->query("SELECT disease_name,COUNT(*) AS c FROM disease_records WHERE disease_name IS NOT NULL AND TRIM(disease_name)!='' GROUP BY disease_name ORDER BY c DESC LIMIT 6")->fetchAll(PDO::FETCH_ASSOC);
    foreach ($dis_breakdown as &$di) $di['c'] = (int)$di['c']; unset($di);
} catch (PDOException $e) {}

// ── TODAY stats ─────────────────────────────────────────────────────────────────
$today_scans = 0; $today_active = 0; $today_done = 0; $today_top_dis = 'N/A';
try {
    $today_scans = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE DATE(scanned_at)=CURDATE()")->fetchColumn();
    if ($has_stat) {
        $today_active = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE DATE(scanned_at)=CURDATE() AND status='in_progress'")->fetchColumn();
        $today_done   = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE DATE(scanned_at)=CURDATE() AND status='recovered'")->fetchColumn();
    }
    $td = $pdo->query("SELECT disease_name,COUNT(*) c FROM disease_records WHERE DATE(scanned_at)=CURDATE() AND disease_name IS NOT NULL AND TRIM(disease_name)!='' GROUP BY disease_name ORDER BY c DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);
    if ($td) $today_top_dis = $td['disease_name'];
} catch (PDOException $e) {}

// ── MONTH stats ─────────────────────────────────────────────────────────────────
$month_scans = 0; $month_rec_rate = 0; $month_top_plant = 'N/A'; $month_top_dis = 'N/A'; $month_recovered = 0;
try {
    $month_scans = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE YEAR(scanned_at)=YEAR(NOW()) AND MONTH(scanned_at)=MONTH(NOW())")->fetchColumn();
    if ($has_stat) {
        $month_recovered = (int)$pdo->query("SELECT COUNT(*) FROM disease_records WHERE YEAR(scanned_at)=YEAR(NOW()) AND MONTH(scanned_at)=MONTH(NOW()) AND status='recovered'")->fetchColumn();
        $month_rec_rate  = $month_scans > 0 ? (int)round(($month_recovered / $month_scans) * 100) : 0;
    }
    if ($has_plant) {
        $r = $pdo->query("SELECT plant_name,COUNT(*) c FROM disease_records WHERE YEAR(scanned_at)=YEAR(NOW()) AND MONTH(scanned_at)=MONTH(NOW()) AND plant_name IS NOT NULL AND TRIM(plant_name)!='' GROUP BY plant_name ORDER BY c DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);
        if ($r) $month_top_plant = $r['plant_name'];
    }
    $r = $pdo->query("SELECT disease_name,COUNT(*) c FROM disease_records WHERE YEAR(scanned_at)=YEAR(NOW()) AND MONTH(scanned_at)=MONTH(NOW()) AND disease_name IS NOT NULL AND TRIM(disease_name)!='' GROUP BY disease_name ORDER BY c DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);
    if ($r) $month_top_dis = $r['disease_name'];
} catch (PDOException $e) {}

// ══════════════════════════════════════════════════════════════════════════════
//  SYSTEM INSIGHTS DATA
// ══════════════════════════════════════════════════════════════════════════════
// 1. Urgent: in_progress > 7 days
$urgent_cases = [];
if ($has_stat) {
    $pu = $has_plant ? 'dr.plant_name,' : "'' AS plant_name,";
    try {
        $urgent_cases = $pdo->query("
            SELECT dr.id, $pu dr.disease_name, u.name AS user_name, dr.scanned_at,
                   DATEDIFF(NOW(), dr.scanned_at) AS days_ago
            FROM disease_records dr JOIN users u ON dr.user_id=u.id
            WHERE dr.status='in_progress' AND DATEDIFF(NOW(), dr.scanned_at) > 7
            ORDER BY days_ago DESC LIMIT 8
        ")->fetchAll(PDO::FETCH_ASSOC);
    } catch (PDOException $e) {}
}

// 2. Repeat infections (same user + same disease, count > 1)
$repeat_inf = [];
try {
    $repeat_inf = $pdo->query("
        SELECT u.name AS user_name, dr.disease_name, COUNT(*) AS cnt
        FROM disease_records dr JOIN users u ON dr.user_id=u.id
        WHERE dr.disease_name IS NOT NULL AND TRIM(dr.disease_name) != ''
        GROUP BY dr.user_id, dr.disease_name HAVING cnt > 1 ORDER BY cnt DESC LIMIT 8
    ")->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {}

// 3. Top 5 most active users
$top_users = [];
try {
    $top_users = $pdo->query("
        SELECT u.name, u.email, COUNT(*) AS scans,
               SUM(CASE WHEN dr.status='recovered' THEN 1 ELSE 0 END) AS recovered_cnt
        FROM disease_records dr JOIN users u ON dr.user_id=u.id
        GROUP BY dr.user_id ORDER BY scans DESC LIMIT 5
    ")->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {}

$most_active = $top_users[0] ?? ['name' => 'N/A', 'scans' => 0];

// ══════════════════════════════════════════════════════════════════════════════
//  USERS LIST
// ══════════════════════════════════════════════════════════════════════════════
$all_users = [];
try { $all_users = $pdo->query("SELECT id,name,email,role,created_at FROM users ORDER BY created_at DESC")->fetchAll(); } catch (PDOException $e) {}

// ── Per-user records map (for JS print modal) ─────────────────────────────────
$user_records_json = '{}';
try {
    $pc3 = $has_plant ? 'dr.plant_name' : "'' AS plant_name";
    $cc3 = $has_conf  ? 'dr.confidence' : "0 AS confidence";
    $sc3 = $has_stat  ? 'dr.status'     : "'detected' AS status";
    $dc3 = $has_days  ? 'dr.estimated_days' : "NULL AS estimated_days";
    $tc3 = $has_treat ? 'dr.treatment'  : "'' AS treatment";
    $urecs = $pdo->query("SELECT dr.user_id,dr.id,$pc3,dr.disease_name,$cc3,$sc3,$tc3,dr.scanned_at,$dc3
        FROM disease_records dr ORDER BY dr.scanned_at DESC LIMIT 2000")->fetchAll(PDO::FETCH_ASSOC);
    $urmap = [];
    foreach ($urecs as $ur) {
        $uid2 = (int)$ur['user_id'];
        if (!isset($urmap[$uid2])) $urmap[$uid2] = [];
        $urmap[$uid2][] = [
            'id'            => (int)$ur['id'],
            'plant_name'    => (string)($ur['plant_name'] ?? ''),
            'disease_name'  => (string)($ur['disease_name'] ?? ''),
            'confidence'    => (float)($ur['confidence'] ?? 0),
            'status'        => (string)($ur['status'] ?? 'detected'),
            'treatment'     => (string)($ur['treatment'] ?? ''),
            'estimated_days'=> isset($ur['estimated_days']) ? (int)$ur['estimated_days'] : null,
            'scanned_at'    => (string)($ur['scanned_at'] ?? ''),
        ];
    }
   $user_records_json = json_encode($urmap, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP);
   if ($user_records_json === false) { $user_records_json = "{}"; }
} catch (PDOException $e) { $user_records_json = '{}'; }

// ══════════════════════════════════════════════════════════════════════════════
//  ADVANCED LOGS — search / filter / sort
// ══════════════════════════════════════════════════════════════════════════════
$fq     = trim($_GET['q']       ?? '');
$fstat  = trim($_GET['fstat']   ?? '');
$fplant = trim($_GET['fplant']  ?? '');
$fuser  = trim($_GET['fuser']   ?? '');
$fdfrom = trim($_GET['dfrom']   ?? '');
$fdto   = trim($_GET['dto']     ?? '');
$fsort  = trim($_GET['sort']    ?? 'latest');

// Build dynamic SELECT
$lc = ['dr.id', 'u.name AS user_name', 'u.email AS user_email'];
if ($has_plant)  $lc[] = 'dr.plant_name';
$lc[] = 'dr.disease_name';
if ($has_conf)   $lc[] = 'dr.confidence';
if ($has_stat)   $lc[] = 'dr.status';
if ($has_days)   $lc[] = 'dr.estimated_days';
if ($has_treat)  $lc[] = 'dr.treatment';
if ($has_next)   $lc[] = 'dr.next_reminder';
$lc[] = 'dr.scanned_at';
$lsel = implode(', ', $lc);

// Build WHERE
$wp = ['1=1']; $bp = [];
if ($fq !== '') {
    $lk = '%'.$fq.'%';
    $parts = ['u.name LIKE ?','u.email LIKE ?','dr.disease_name LIKE ?'];
    if ($has_plant) $parts[] = 'dr.plant_name LIKE ?';
    $wp[] = '('.implode(' OR ',$parts).')';
    $bp[] = $lk; $bp[] = $lk; $bp[] = $lk;
    if ($has_plant) $bp[] = $lk;
}
if ($fstat  !== '' && $has_stat)  { $wp[] = 'dr.status=?';     $bp[] = $fstat;  }
if ($fplant !== '' && $has_plant) { $wp[] = 'dr.plant_name=?'; $bp[] = $fplant; }
if ($fuser  !== '')               { $wp[] = 'u.name=?';        $bp[] = $fuser;  }
if ($fdfrom !== '')               { $wp[] = 'DATE(dr.scanned_at)>=?'; $bp[] = $fdfrom; }
if ($fdto   !== '')               { $wp[] = 'DATE(dr.scanned_at)<=?'; $bp[] = $fdto;   }
$wsql = implode(' AND ', $wp);

$osql = match($fsort) {
    'disease'  => 'dr.disease_name ASC, dr.scanned_at DESC',
    'recovery' => $has_stat ? "FIELD(dr.status,'in_progress','detected','recovered') ASC, dr.scanned_at DESC" : 'dr.scanned_at DESC',
    default    => 'dr.scanned_at DESC',
};

$log_recs = []; $log_total = 0;
try {
    $cs = $pdo->prepare("SELECT COUNT(*) FROM disease_records dr JOIN users u ON dr.user_id=u.id WHERE $wsql");
    $cs->execute($bp); $log_total = (int)$cs->fetchColumn();
    $ls = $pdo->prepare("SELECT $lsel FROM disease_records dr JOIN users u ON dr.user_id=u.id WHERE $wsql ORDER BY $osql LIMIT 500");
    $ls->execute($bp); $log_recs = $ls->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {}

foreach ($log_recs as &$lr) {
    if (!isset($lr['status']))     $lr['status']     = 'detected';
    if (!isset($lr['plant_name'])) $lr['plant_name']  = '';
    if (!isset($lr['confidence'])) $lr['confidence']  = 0;
} unset($lr);

// Filter dropdown data
$plant_opts = [];
if ($has_plant) { try { $plant_opts = $pdo->query("SELECT DISTINCT plant_name FROM disease_records WHERE plant_name IS NOT NULL AND TRIM(plant_name)!='' ORDER BY plant_name")->fetchAll(PDO::FETCH_COLUMN); } catch (PDOException $e) {} }
$user_opts = [];
try { $user_opts = $pdo->query("SELECT DISTINCT name FROM users WHERE role='user' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN); } catch (PDOException $e) {}

// ══════════════════════════════════════════════════════════════════════════════
//  ORDERS DATA  — medicine_orders + medicine_order_items
// ══════════════════════════════════════════════════════════════════════════════
$orders_exist = false;
try {
    $pdo->query("SELECT 1 FROM medicine_orders LIMIT 1");
    $orders_exist = true;
} catch (PDOException $e) { $orders_exist = false; }

$all_orders   = [];
$ttl_orders   = 0;
$ttl_pending  = 0;
$ttl_revenue  = 0.0;
$orders_today = 0;

if ($orders_exist) {
    try {
        $ttl_orders  = (int)$pdo->query("SELECT COUNT(*) FROM medicine_orders")->fetchColumn();
        $ttl_pending = (int)$pdo->query("SELECT COUNT(*) FROM medicine_orders WHERE status='pending'")->fetchColumn();
        $ttl_revenue = (float)$pdo->query("SELECT COALESCE(SUM(total_price),0) FROM medicine_orders WHERE status!='cancelled'")->fetchColumn();
        $orders_today= (int)$pdo->query("SELECT COUNT(*) FROM medicine_orders WHERE DATE(ordered_at)=CURDATE()")->fetchColumn();
    } catch (PDOException $e) {}

    // Update status action
    if ($sec === 'orders' && isset($_GET['order_status'], $_GET['oid'])) {
        $allowed_st = ['pending','confirmed','shipped','delivered','cancelled'];
        $new_st = $_GET['order_status'];
        if (in_array($new_st, $allowed_st)) {
            try { $pdo->prepare("UPDATE medicine_orders SET status=? WHERE id=?")->execute([$new_st, (int)$_GET['oid']]); }
            catch (PDOException $e) {}
        }
        header("Location: admin.php?section=orders&flash=order_updated"); exit;
    }

    // Fetch orders with item details
    $ord_fstat = trim($_GET['ord_fstat'] ?? '');
    $ord_q     = trim($_GET['ord_q']     ?? '');
    $ord_wp = ['1=1']; $ord_bp = [];
    if ($ord_fstat !== '') { $ord_wp[] = 'o.status=?'; $ord_bp[] = $ord_fstat; }
    if ($ord_q     !== '') { $lk2='%'.$ord_q.'%'; $ord_wp[]='(o.user_name LIKE ? OR o.user_email LIKE ?)'; $ord_bp[]=$lk2; $ord_bp[]=$lk2; }
    $ord_wsql = implode(' AND ', $ord_wp);

    try {
        $all_orders = $pdo->prepare("
            SELECT o.id, o.user_id, o.user_name, o.user_email,
                   o.total_price, o.item_count, o.status, o.admin_note, o.ordered_at
            FROM medicine_orders o
            WHERE $ord_wsql
            ORDER BY o.ordered_at DESC LIMIT 500
        ");
        $all_orders->execute($ord_bp);
        $all_orders = $all_orders->fetchAll(PDO::FETCH_ASSOC);
    } catch (PDOException $e) { $all_orders = []; }

    // Fetch all items (for order detail popup)
    $order_items_map = [];
    try {
        $oi = $pdo->query("SELECT * FROM medicine_order_items ORDER BY order_id, id");
        foreach ($oi->fetchAll(PDO::FETCH_ASSOC) as $oi_row) {
            $order_items_map[(int)$oi_row['order_id']][] = $oi_row;
        }
    } catch (PDOException $e) {}
}

$flash_msgs['order_updated'] = ['type'=>'ok', 'text'=>'✓ Order status updated successfully.'];

// ── Flash message ──────────────────────────────────────────────────────────────
$flash = $_GET['flash'] ?? '';
$flash_msgs = [
    'deleted' => ['type'=>'ok', 'text'=>'✓ Record deleted successfully.'],
    'cleared' => ['type'=>'ok', 'text'=>'✓ User records cleared successfully.'],
];
$flash_data = $flash_msgs[$flash] ?? null;

?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Admin Panel — BATANOX</title>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  /* greens */
  --g50:#f0fdf4;--g100:#dcfce7;--g200:#bbf7d0;--g300:#86efac;
  --g400:#4ade80;--g500:#22c55e;--g600:#16a34a;--g700:#15803d;--g800:#166534;--g900:#14532d;
  /* grays */
  --gr25:#fafafa;--gr50:#f9fafb;--gr100:#f3f4f6;--gr150:#eef0f2;--gr200:#e5e7eb;
  --gr300:#d1d5db;--gr400:#9ca3af;--gr500:#6b7280;--gr600:#4b5563;--gr700:#374151;
  --gr800:#1f2937;--gr900:#111827;
  /* accent */
  --r50:#fef2f2;--r100:#fee2e2;--r200:#fecaca;--r300:#fca5a5;--r500:#ef4444;--r600:#dc2626;--r700:#b91c1c;
  --b50:#eff6ff;--b100:#dbeafe;--b200:#bfdbfe;--b400:#60a5fa;--b500:#3b82f6;--b600:#2563eb;--b700:#1d4ed8;
  --y50:#fefce8;--y100:#fef9c3;--y400:#facc15;--y500:#eab308;--y600:#ca8a04;--y700:#a16207;
  --o50:#fff7ed;--o100:#ffedd5;--o200:#fed7aa;--o500:#f97316;--o600:#ea580c;--o700:#c2410c;
  --p50:#faf5ff;--p100:#f3e8ff;--p200:#e9d5ff;--p500:#a855f7;--p600:#9333ea;--p700:#7e22ce;
  --t50:#f0fdfa;--t100:#ccfbf1;--t500:#14b8a6;--t600:#0d9488;--t700:#0f766e;
  /* layout */
  --sidebar-w:258px;
  --topbar-h:62px;
  --shadow-xs:0 1px 2px rgba(0,0,0,.06);
  --shadow-sm:0 1px 3px rgba(0,0,0,.08),0 1px 2px rgba(0,0,0,.05);
  --shadow-md:0 4px 16px rgba(0,0,0,.08),0 2px 6px rgba(0,0,0,.04);
  --shadow-lg:0 12px 40px rgba(0,0,0,.1),0 4px 16px rgba(0,0,0,.06);
  --white:#fff;
}

/* ────────────────── BASE ────────────────── */
body{font-family:'Plus Jakarta Sans',sans-serif;background:var(--gr50);color:var(--gr900);line-height:1.5;min-height:100vh}
a{text-decoration:none;color:inherit}

/* ────────────────── SIDEBAR ────────────────── */
.sb{position:fixed;inset:0 auto 0 0;width:var(--sidebar-w);background:var(--gr900);display:flex;flex-direction:column;z-index:300;overflow-y:auto}
.sb-brand{display:flex;align-items:center;gap:10px;padding:20px 18px 18px;border-bottom:1px solid rgba(255,255,255,.07)}
.sb-logo{width:34px;height:34px;background:linear-gradient(135deg,var(--g600),var(--g500));border-radius:9px;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 14px rgba(34,197,94,.35);flex-shrink:0}
.sb-logo svg{width:17px;height:17px;fill:white}
.sb-name{font-size:18px;font-weight:800;color:white;letter-spacing:-.3px}
.sb-name span{color:var(--g400)}
.sb-nav{flex:1;padding:14px 10px}
.sb-grp{margin-bottom:20px}
.sb-grp-lbl{font-size:9.5px;font-weight:700;color:rgba(255,255,255,.28);text-transform:uppercase;letter-spacing:1.3px;padding:0 10px;margin-bottom:6px}
.sb-link{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:8px;font-size:13px;font-weight:600;color:rgba(255,255,255,.52);transition:all .15s;margin-bottom:1px;position:relative;cursor:pointer}
.sb-link:hover{background:rgba(255,255,255,.07);color:rgba(255,255,255,.88)}
.sb-link.on{background:rgba(34,197,94,.16);color:var(--g400)}
.sb-link.on::before{content:'';position:absolute;left:0;top:50%;transform:translateY(-50%);width:3px;height:60%;background:var(--g400);border-radius:0 2px 2px 0}
.sb-ico{font-size:14px;width:18px;text-align:center;flex-shrink:0}
.sb-cnt{margin-left:auto;font-size:10px;font-weight:700;padding:2px 7px;border-radius:10px;background:rgba(255,255,255,.1);color:rgba(255,255,255,.55)}
.sb-cnt.alert{background:rgba(239,68,68,.25);color:#fca5a5}
.sb-foot{padding:14px 12px;border-top:1px solid rgba(255,255,255,.07)}
.sb-user{display:flex;align-items:center;gap:9px;padding:10px 10px;border-radius:9px;background:rgba(255,255,255,.05)}
.sb-ava{width:30px;height:30px;border-radius:50%;background:linear-gradient(135deg,var(--g700),var(--g500));display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:800;color:white;flex-shrink:0}
.sb-user-nm{font-size:12px;font-weight:700;color:white}
.sb-user-rl{font-size:10px;color:var(--g400);font-weight:600;letter-spacing:.3px;text-transform:uppercase}
.sb-signout{display:block;text-align:center;margin-top:8px;font-size:11px;color:rgba(255,255,255,.3);font-weight:600;transition:color .15s}
.sb-signout:hover{color:#fca5a5}

/* ────────────────── MAIN ────────────────── */
.main{margin-left:var(--sidebar-w);min-height:100vh;display:flex;flex-direction:column}
.topbar{background:white;border-bottom:1px solid var(--gr200);height:var(--topbar-h);padding:0 28px;display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:200;box-shadow:var(--shadow-xs)}
.tb-left h1{font-size:18px;font-weight:800;letter-spacing:-.4px}
.tb-left p{font-size:11px;color:var(--gr500);margin-top:1px}
.tb-right{display:flex;align-items:center;gap:8px}
.chip{display:inline-flex;align-items:center;gap:4px;padding:4px 10px;border-radius:20px;font-size:11px;font-weight:700}
.chip-g{background:var(--g100);color:var(--g700)}
.chip-b{background:var(--b100);color:var(--b700)}
.chip-r{background:var(--r100);color:var(--r700)}
.chip-y{background:var(--y100);color:var(--y700)}
.chip-o{background:var(--o100);color:var(--o700)}
.content{padding:24px 28px;flex:1}

/* ────────────────── FLASH ────────────────── */
.flash{padding:11px 15px;border-radius:9px;font-size:13px;font-weight:500;margin-bottom:20px;display:flex;align-items:center;gap:8px;border:1px solid transparent}
.flash-ok{background:var(--g50);border-color:var(--g200);color:var(--g700)}

/* ────────────────── HERO BANNERS ────────────────── */
.hero{border-radius:16px;padding:26px 32px;color:white;margin-bottom:22px;position:relative;overflow:hidden}
.hero::after{content:'';position:absolute;top:-60px;right:-40px;width:220px;height:220px;border-radius:50%;background:rgba(255,255,255,.04);pointer-events:none}
.hero-pill{display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.2);border-radius:20px;padding:3px 11px;font-size:10px;font-weight:700;margin-bottom:10px;letter-spacing:.7px;text-transform:uppercase}
.hero h2{font-size:20px;font-weight:800;letter-spacing:-.4px;margin-bottom:4px}
.hero p{font-size:12.5px;opacity:.78}
.hero-green{background:linear-gradient(135deg,#064e3b 0%,var(--g700) 55%,var(--g600) 100%)}
.hero-blue{background:linear-gradient(135deg,#1e3a8a 0%,var(--b700) 55%,var(--b500) 100%)}
.hero-orange{background:linear-gradient(135deg,#7c2d12 0%,var(--o700) 55%,var(--o500) 100%)}
.hero-purple{background:linear-gradient(135deg,#3b0764 0%,var(--p700) 55%,var(--p500) 100%)}

/* ────────────────── STAT CARDS ────────────────── */
.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(165px,1fr));gap:14px;margin-bottom:22px}
.card{background:white;border:1px solid var(--gr200);border-radius:13px;padding:18px 18px 16px;position:relative;overflow:hidden;transition:transform .14s,box-shadow .14s;box-shadow:var(--shadow-sm)}
.card:hover{transform:translateY(-2px);box-shadow:var(--shadow-md)}
.card::before{content:'';position:absolute;top:0;left:0;right:0;height:3px;border-radius:13px 13px 0 0}
.c-users::before{background:linear-gradient(90deg,var(--b500),var(--b400))}
.c-scans::before{background:linear-gradient(90deg,var(--g600),var(--g400))}
.c-active::before{background:linear-gradient(90deg,var(--y500),var(--y400))}
.c-rec::before{background:linear-gradient(90deg,var(--t600),var(--t500))}
.c-today::before{background:linear-gradient(90deg,var(--p600),var(--p500))}
.c-growth::before{background:linear-gradient(90deg,var(--o600),var(--o500))}
.card-ico{width:36px;height:36px;border-radius:9px;display:flex;align-items:center;justify-content:center;font-size:16px;margin-bottom:11px}
.c-users .card-ico{background:var(--b50)}.c-scans .card-ico{background:var(--g50)}.c-active .card-ico{background:var(--y50)}.c-rec .card-ico{background:var(--t50)}.c-today .card-ico{background:var(--p50)}.c-growth .card-ico{background:var(--o50)}
.card-val{font-size:28px;font-weight:800;letter-spacing:-1px;color:var(--gr900);margin-bottom:3px;line-height:1}
.card-lbl{font-size:12px;font-weight:600;color:var(--gr500)}
.card-sub{font-size:10.5px;color:var(--gr400);margin-top:3px}
.card-badge{position:absolute;top:14px;right:14px;font-size:10px;font-weight:700;padding:2px 7px;border-radius:8px}
.cb-up{background:var(--g100);color:var(--g700)}.cb-dn{background:var(--r100);color:var(--r700)}.cb-warn{background:var(--y100);color:var(--y700)}

/* ────────────────── INSIGHT TRIO ────────────────── */
.trio{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;margin-bottom:22px}
.trio-card{background:white;border:1px solid var(--gr200);border-radius:13px;padding:18px 20px;box-shadow:var(--shadow-sm)}
.trio-lbl{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.8px;color:var(--gr400);margin-bottom:8px}
.trio-val{font-size:17px;font-weight:800;color:var(--gr900);letter-spacing:-.2px;word-break:break-word}
.trio-cnt{font-size:11px;font-weight:700;color:var(--g600);margin-top:4px}
.trio-sub{font-size:11px;color:var(--gr500);margin-top:3px}
.trio-bar-wrap{height:4px;background:var(--gr100);border-radius:4px;overflow:hidden;margin-top:10px}
.trio-bar-fill{height:100%;border-radius:4px;background:linear-gradient(90deg,var(--g600),var(--g400));transition:width .7s ease}

/* ────────────────── BAR CHART ────────────────── */
.barchart{background:white;border:1px solid var(--gr200);border-radius:13px;margin-bottom:22px;overflow:hidden;box-shadow:var(--shadow-sm)}
.bc-head{padding:14px 20px;border-bottom:1px solid var(--gr100);display:flex;align-items:center;justify-content:space-between}
.bc-title{font-size:14px;font-weight:700;color:var(--gr900)}
.bc-row{display:flex;align-items:center;gap:12px;padding:10px 20px;border-bottom:1px solid var(--gr100)}
.bc-row:last-child{border-bottom:none}
.bc-lbl{font-size:12.5px;font-weight:600;color:var(--gr700);flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.bc-track{flex:2;height:7px;background:var(--gr100);border-radius:6px;overflow:hidden}
.bc-fill{height:100%;border-radius:6px;background:linear-gradient(90deg,var(--g700),var(--g400));transition:width .7s ease}
.bc-num{font-size:12px;font-weight:700;color:var(--gr600);min-width:28px;text-align:right}

/* ────────────────── PANEL / SECTION ────────────────── */
.panel{background:white;border:1px solid var(--gr200);border-radius:13px;margin-bottom:22px;overflow:hidden;box-shadow:var(--shadow-sm)}
.panel-head{padding:15px 20px;border-bottom:1px solid var(--gr100);display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px}
.panel-title{font-size:14px;font-weight:700;color:var(--gr900);display:flex;align-items:center;gap:7px}
.panel-sub{font-size:11px;color:var(--gr400);font-weight:400;margin-left:4px}

/* ────────────────── TABLE ────────────────── */
.t-wrap{overflow-x:auto}
table{width:100%;border-collapse:collapse;font-size:12.5px}
th{padding:10px 14px;text-align:left;font-size:10px;font-weight:700;color:var(--gr500);text-transform:uppercase;letter-spacing:.7px;background:var(--gr50);border-bottom:1px solid var(--gr200);white-space:nowrap}
td{padding:11px 14px;border-bottom:1px solid var(--gr100);color:var(--gr700);vertical-align:middle}
tr:last-child td{border-bottom:none}
tr:hover td{background:var(--gr25)}
.tbtn{font-size:11px;font-weight:700;padding:4px 9px;border-radius:6px;display:inline-block;border:none;cursor:pointer;font-family:inherit;transition:all .12s;text-decoration:none;margin-right:3px}
.tbtn-del{color:var(--r700);background:var(--r50)}.tbtn-del:hover{background:var(--r100)}
.tbtn-clr{color:var(--gr700);background:var(--gr100)}.tbtn-clr:hover{background:var(--gr200)}
.empty-box{padding:48px 20px;text-align:center;color:var(--gr400)}
.empty-box-ico{font-size:34px;margin-bottom:10px}
.empty-box p{font-size:13px}

/* ────────────────── STATUS BADGE ────────────────── */
.s-badge{display:inline-flex;align-items:center;gap:5px;padding:3px 9px;border-radius:20px;font-size:11px;font-weight:700;white-space:nowrap}
.s-dot{width:6px;height:6px;border-radius:50%;flex-shrink:0}

/* ────────────────── CONFIDENCE BAR ────────────────── */
.conf-bar{display:flex;align-items:center;gap:7px}
.conf-track{width:48px;height:5px;background:var(--gr100);border-radius:4px;overflow:hidden;flex-shrink:0}
.conf-fill{height:100%;border-radius:4px}
.cf-high{background:var(--g500)}.cf-mid{background:var(--y500)}.cf-low{background:var(--r500)}

/* ────────────────── PROGRESS BAR ────────────────── */
.pbar{height:5px;background:var(--gr100);border-radius:4px;overflow:hidden;margin-top:5px}
.pbar-fill{height:100%;border-radius:4px;transition:width .6s ease}
.pf-green{background:linear-gradient(90deg,var(--g600),var(--g400))}
.pf-blue{background:linear-gradient(90deg,var(--b600),var(--b400))}
.pf-orange{background:linear-gradient(90deg,var(--o600),var(--o400,#fb923c))}
.pf-red{background:linear-gradient(90deg,var(--r600),var(--r400,#f87171))}

/* ────────────────── FILTER ZONE ────────────────── */
.fzone{padding:16px 20px;border-bottom:1px solid var(--gr100);background:var(--gr25)}
.frow{display:flex;align-items:flex-end;gap:10px;flex-wrap:wrap}
.fg{display:flex;flex-direction:column;gap:4px}
.fg label{font-size:10px;font-weight:700;color:var(--gr600);text-transform:uppercase;letter-spacing:.5px}
.finput,.fsel{padding:7px 10px;border:1.5px solid var(--gr300);border-radius:8px;font-family:inherit;font-size:12.5px;color:var(--gr900);background:white;outline:none;transition:border-color .13s}
.finput:focus,.fsel:focus{border-color:var(--g500);box-shadow:0 0 0 3px rgba(34,197,94,.1)}
.finput{width:200px}.fsel{min-width:130px}
input[type="date"]{min-width:135px}
.fbtn{padding:7px 15px;background:var(--g700);color:white;border:none;border-radius:8px;font-family:inherit;font-size:12.5px;font-weight:700;cursor:pointer;transition:background .13s;align-self:flex-end;white-space:nowrap}
.fbtn:hover{background:var(--g800)}
.freset{padding:7px 12px;background:var(--gr100);color:var(--gr700);border:1.5px solid var(--gr300);border-radius:8px;font-family:inherit;font-size:12px;font-weight:600;cursor:pointer;text-decoration:none;align-self:flex-end;transition:all .13s}
.freset:hover{background:var(--gr200)}

/* ────────────────── META / EXPORT BAR ────────────────── */
.meta-bar{padding:10px 20px;border-bottom:1px solid var(--gr100);display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px;font-size:12px;color:var(--gr500)}
.exp-bar{display:flex;gap:7px;align-items:center}
.expbtn{display:inline-flex;align-items:center;gap:5px;padding:6px 13px;border-radius:8px;font-size:11.5px;font-weight:700;border:none;cursor:pointer;font-family:inherit;transition:all .13s;text-decoration:none}
.exp-csv{background:#dcfce7;color:#15803d}.exp-csv:hover{background:#bbf7d0}
.exp-pdf{background:#fee2e2;color:#b91c1c}.exp-pdf:hover{background:#fecaca}
.exp-print{background:#dbeafe;color:#1d4ed8}.exp-print:hover{background:#bfdbfe}

/* ────────────────── REPORTS GRID ────────────────── */
.rep-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-bottom:22px}
.rep-card{background:white;border:1px solid var(--gr200);border-radius:13px;overflow:hidden;box-shadow:var(--shadow-sm)}
.rep-head{padding:16px 20px;border-bottom:1px solid var(--gr100);display:flex;align-items:center;gap:10px}
.rep-head-ico{width:38px;height:38px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:17px;flex-shrink:0}
.rep-head-title{font-size:14px;font-weight:700;color:var(--gr900)}
.rep-head-sub{font-size:11px;color:var(--gr500)}
.rep-body{padding:18px 20px;display:grid;grid-template-columns:1fr 1fr;gap:12px}
.rstat{background:var(--gr50);border-radius:10px;padding:13px 14px}
.rstat-val{font-size:22px;font-weight:800;letter-spacing:-.5px;color:var(--gr900)}
.rstat-lbl{font-size:10.5px;font-weight:600;color:var(--gr500);margin-top:2px}
.rstat-full{grid-column:1/-1}

/* ────────────────── INSIGHTS GRID ────────────────── */
.ins-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-bottom:22px}
.ins-card{background:white;border:1px solid var(--gr200);border-radius:13px;overflow:hidden;box-shadow:var(--shadow-sm)}
.ins-head{padding:13px 18px;border-bottom:1px solid var(--gr100);display:flex;align-items:center;gap:8px}
.ins-head-lbl{font-size:13px;font-weight:700;color:var(--gr900);flex:1}
.ins-head-cnt{font-size:10px;font-weight:700;padding:2px 8px;border-radius:8px}
.ins-item{display:flex;align-items:flex-start;gap:10px;padding:11px 18px;border-bottom:1px solid var(--gr100)}
.ins-item:last-child{border-bottom:none}
.ins-ico{width:30px;height:30px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0}
.ins-body{flex:1;min-width:0}
.ins-main{font-size:12.5px;font-weight:700;color:var(--gr900)}
.ins-sub{font-size:11px;color:var(--gr500);margin-top:2px}
.ins-badge{margin-left:auto;font-size:10px;font-weight:700;padding:3px 8px;border-radius:8px;white-space:nowrap;flex-shrink:0}
.ib-r{background:var(--r50);color:var(--r700)}.ib-o{background:var(--o50);color:var(--o700)}.ib-b{background:var(--b50);color:var(--b700)}.ib-g{background:var(--g100);color:var(--g700)}.ib-p{background:var(--p50);color:var(--p700)}

/* ────────────────── RECOVERY CONFIDENCE INDICATOR ────────────────── */
.rci-wrap{display:flex;flex-direction:column;gap:5px}
.rci-badge{display:inline-flex;align-items:center;gap:6px;padding:4px 10px;border-radius:20px;font-size:11px;font-weight:700;white-space:nowrap}
.rci-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0;animation:rcipulse 2s ease-in-out infinite}
@keyframes rcipulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.6;transform:scale(1.3)}}
/* Detected — Red */
.rci-detected{background:#fef2f2;color:#991b1b;border:1px solid #fecaca}
.rci-detected .rci-dot{background:#ef4444}
/* In Progress — Orange */
.rci-progress{background:#fff7ed;color:#9a3412;border:1px solid #fed7aa}
.rci-progress .rci-dot{background:#f97316}
/* Recovered — Green */
.rci-recovered{background:#f0fdf4;color:#166534;border:1px solid #bbf7d0}
.rci-recovered .rci-dot{background:#22c55e;animation:none}
/* Recovery bar under badge */
.rci-bar{height:4px;border-radius:4px;overflow:hidden;background:var(--gr100)}
.rci-bar-fill{height:100%;border-radius:4px;transition:width .6s ease}
.rci-fill-det{background:linear-gradient(90deg,#ef4444,#fca5a5)}
.rci-fill-prog{background:linear-gradient(90deg,#f97316,#fdba74)}
.rci-fill-rec{background:linear-gradient(90deg,#16a34a,#4ade80)}

/* ────────────────── USER PRINT MODAL ────────────────── */
.pmodal-bg{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:1000;display:none;align-items:center;justify-content:center;padding:20px}
.pmodal-bg.open{display:flex}
.pmodal{background:white;border-radius:16px;width:100%;max-width:820px;max-height:90vh;display:flex;flex-direction:column;box-shadow:0 24px 64px rgba(0,0,0,.18)}
.pmodal-head{padding:18px 24px;border-bottom:1px solid var(--gr200);display:flex;align-items:center;justify-content:space-between;flex-shrink:0}
.pmodal-title{font-size:15px;font-weight:800;color:var(--gr900)}
.pmodal-sub{font-size:11px;color:var(--gr500);margin-top:2px}
.pmodal-close{width:30px;height:30px;border-radius:8px;border:none;background:var(--gr100);color:var(--gr600);font-size:16px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all .13s}
.pmodal-close:hover{background:var(--r100);color:var(--r700)}
.pmodal-body{padding:20px 24px;overflow-y:auto;flex:1}
.pmodal-foot{padding:14px 24px;border-top:1px solid var(--gr200);display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;flex-shrink:0}
/* Print report header (shown only when printing modal) */
.prpt-head{display:none;margin-bottom:20px;padding-bottom:14px;border-bottom:2px solid #ddd;text-align:center}
.prpt-head h2{font-size:20px;font-weight:800}.prpt-head p{font-size:12px;color:#555;margin-top:3px}

@media print{
  .sb,.topbar,.fzone,.exp-bar,.meta-bar .exp-bar,.tbtn,.fbtn,.freset,.no-print,.pmodal-head,.pmodal-foot{display:none!important}
  .main{margin-left:0}
  .content{padding:0}
  body{background:white}
  .panel,.barchart,.rep-card,.ins-card,.card{box-shadow:none;border:1px solid #ddd}
  .phdr{display:block!important}
  /* If printing from inside modal */
  .pmodal-bg.printing{position:static;background:none;display:block!important;padding:0}
  .pmodal-bg.printing .pmodal{max-height:none;box-shadow:none;border-radius:0}
  .pmodal-bg.printing .prpt-head{display:block!important}
}

/* ────────────────── RESPONSIVE ────────────────── */
@media(max-width:1100px){.trio{grid-template-columns:1fr 1fr}.ins-grid{grid-template-columns:1fr}.rep-grid{grid-template-columns:1fr}}
@media(max-width:700px){.trio{grid-template-columns:1fr}.card-grid{grid-template-columns:1fr 1fr}}
</style>
</head>
<body>

<!-- ══════════════════════ SIDEBAR ══════════════════════ -->
<aside class="sb">
  <div class="sb-brand">
    <div class="sb-logo"><svg viewBox="0 0 24 24"><path d="M17 8C8 10 5.9 16.17 3.82 21.34L5.71 22l1-2.3A4.49 4.49 0 008 20C19 20 22 3 22 3c-1 2-8 2-13 6 1-2.17 2.64-4.41 8-5z"/></svg></div>
    <div class="sb-name">BATA<span>NOX</span></div>
  </div>

  <nav class="sb-nav">
    <div class="sb-grp">
      <div class="sb-grp-lbl">Overview</div>
      <a href="admin.php?section=dashboard" class="sb-link <?= $sec==='dashboard'?'on':'' ?>">
        <span class="sb-ico">📊</span> Dashboard
      </a>
      <a href="admin.php?section=insights" class="sb-link <?= $sec==='insights'?'on':'' ?>">
        <span class="sb-ico">⚡</span> System Insights
        <?php if (count($urgent_cases) > 0): ?>
        <span class="sb-cnt alert"><?= count($urgent_cases) ?></span>
        <?php endif; ?>
      </a>
    </div>

    <div class="sb-grp">
      <div class="sb-grp-lbl">Detection Data</div>
      <a href="admin.php?section=logs" class="sb-link <?= $sec==='logs'?'on':'' ?>">
        <span class="sb-ico">📋</span> Advanced Logs
        <span class="sb-cnt"><?= $ttl_recs ?></span>
      </a>
      <a href="admin.php?section=users" class="sb-link <?= $sec==='users'?'on':'' ?>">
        <span class="sb-ico">👥</span> Users
        <span class="sb-cnt"><?= count($all_users) ?></span>
      </a>
    </div>

    <div class="sb-grp">
      <div class="sb-grp-lbl">Reporting</div>
      <a href="admin.php?section=reports" class="sb-link <?= $sec==='reports'?'on':'' ?>">
        <span class="sb-ico">📅</span> Daily &amp; Monthly
      </a>
      <a href="admin.php?export=csv" class="sb-link no-print" target="_blank">
        <span class="sb-ico">⬇️</span> Export CSV
      </a>
    </div>

    <div class="sb-grp">
      <div class="sb-grp-lbl">Medicine Store</div>
      <a href="admin.php?section=orders" class="sb-link <?= $sec==='orders'?'on':'' ?>">
        <span class="sb-ico">🛒</span> Medicine Orders
        <?php if ($ttl_pending > 0): ?>
        <span class="sb-cnt alert"><?= $ttl_pending ?> new</span>
        <?php endif; ?>
      </a>
    </div>

    <div class="sb-grp">
      <div class="sb-grp-lbl">App</div>
      <a href="http://localhost:5000" class="sb-link" target="_blank">
        <span class="sb-ico">🔬</span> User Dashboard
      </a>
    </div>
  </nav>

  <div class="sb-foot">
    <div class="sb-user">
      <div class="sb-ava"><?= strtoupper(substr($admin_name,0,1)) ?></div>
      <div>
        <div class="sb-user-nm"><?= safeHtml($admin_name) ?></div>
        <div class="sb-user-rl">Administrator</div>
      </div>
    </div>
    <a href="logout.php" class="sb-signout">← Sign Out</a>
  </div>
</aside>

<!-- ══════════════════════ MAIN ══════════════════════ -->
<div class="main">

  <!-- TOP BAR -->
  <header class="topbar">
    <div class="tb-left">
      <h1><?php echo match($sec){
        'logs'     => '📋 Advanced Detection Logs',
        'reports'  => '📅 Reports &amp; Analytics',
        'insights' => '⚡ System Insights',
        'users'    => '👥 User Management',
        'orders'   => '🛒 Medicine Orders',
        default    => '📊 Admin Dashboard',
      }; ?></h1>
      <p>BATANOX Agricultural Platform &nbsp;·&nbsp; <?= date('D, M j Y · g:i A') ?></p>
    </div>
    <div class="tb-right">
      <span class="chip chip-g">
        <?= $growth_pct >= 0 ? '↑ +'.$growth_pct.'%' : '↓ '.$growth_pct.'%' ?> growth
      </span>
      <?php if (count($urgent_cases) > 0): ?>
      <span class="chip chip-r">🚨 <?= count($urgent_cases) ?> urgent</span>
      <?php endif; ?>
      <span class="chip chip-b">Admin Access</span>
    </div>
  </header>

  <!-- CONTENT -->
  <div class="content">

    <!-- Print header (hidden on screen) -->
    <div class="phdr">
      <h1>🌿 BATANOX — Detection Report</h1>
      <p>Generated by <?= safeHtml($admin_name) ?> &nbsp;·&nbsp; <?= date("F j, Y g:i A") ?></p>
    </div>

    <?php if ($flash_data): ?>
    <div class="flash flash-<?= $flash_data['type'] ?>"><?= safeHtml($flash_data['text']) ?></div>
    <?php endif; ?>

<?php /* ═══════════════════════════════════════════════════════════════════════
         SECTION ▸ DASHBOARD
   ═══════════════════════════════════════════════════════════════════════ */
if ($sec === 'dashboard'): ?>

    <div class="hero hero-green">
      <div class="hero-pill">📊 Real-Time Analytics</div>
      <h2>System Overview Dashboard</h2>
      <p>Live platform data across all users &nbsp;·&nbsp; <?= date('l, F j, Y') ?></p>
    </div>

    <!-- Stat cards row -->
    <div class="card-grid">
      <div class="card c-users">
        <div class="card-ico">👥</div>
        <div class="card-val"><?= $ttl_users ?></div>
        <div class="card-lbl">Registered Users</div>
        <div class="card-sub">Active accounts</div>
      </div>
      <div class="card c-scans">
        <div class="card-ico">🔬</div>
        <div class="card-val"><?= $ttl_recs ?></div>
        <div class="card-lbl">Total Scans</div>
        <div class="card-sub">All-time records</div>
      </div>
      <div class="card c-active">
        <div class="card-ico">💊</div>
        <div class="card-val"><?= $ttl_active ?></div>
        <div class="card-lbl">In Treatment</div>
        <div class="card-sub">Active recovery</div>
        <?php if ($ttl_active > 0): ?>
        <div class="card-badge cb-warn">Active</div>
        <?php endif; ?>
      </div>
      <div class="card c-rec">
        <div class="card-ico">✅</div>
        <div class="card-val"><?= $ttl_recovered ?></div>
        <div class="card-lbl">Recovered</div>
        <div class="card-sub"><?= $rec_rate ?>% success rate</div>
        <div class="card-badge cb-up"><?= $rec_rate ?>%</div>
      </div>
      <div class="card c-today">
        <div class="card-ico">📅</div>
        <div class="card-val"><?= $today_scans ?></div>
        <div class="card-lbl">Scans Today</div>
        <div class="card-sub"><?= date('M j, Y') ?></div>
      </div>
      <div class="card c-growth">
        <div class="card-ico">📈</div>
        <div class="card-val"><?= $growth_pct >= 0 ? '+'.$growth_pct : $growth_pct ?>%</div>
        <div class="card-lbl">30-Day Growth</div>
        <div class="card-sub">vs prior 30 days</div>
        <div class="card-badge <?= $growth_pct >= 0 ? 'cb-up' : 'cb-dn' ?>">
          <?= $growth_pct >= 0 ? '↑ Growing' : '↓ Declining' ?>
        </div>
      </div>
    </div>

    <!-- Insight trio -->
    <div class="trio">
      <div class="trio-card">
        <div class="trio-lbl">🏆 Most Detected Disease</div>
        <div class="trio-val"><?= safeHtml($top_dis_name) ?></div>
        <div class="trio-cnt"><?= $top_dis_cnt ?> occurrences</div>
        <div class="trio-sub">Highest frequency across all users</div>
      </div>
      <div class="trio-card">
        <div class="trio-lbl">🌿 Most Affected Plant</div>
        <div class="trio-val"><?= safeHtml($top_plant_name) ?></div>
        <div class="trio-cnt"><?= $top_plant_cnt ?> records</div>
        <div class="trio-sub">Most commonly scanned species</div>
      </div>
      <div class="trio-card">
        <div class="trio-lbl">📈 Platform Recovery Rate</div>
        <div class="trio-val"><?= $rec_rate ?>%</div>
        <div class="trio-cnt"><?= $ttl_recovered ?> of <?= $ttl_recs ?> cases resolved</div>
        <div class="trio-sub">All-time treatment success</div>
        <div class="trio-bar-wrap">
          <div class="trio-bar-fill" style="width:<?= $rec_rate ?>%"></div>
        </div>
      </div>
    </div>

    <!-- Disease breakdown bar chart -->
    <?php if (!empty($dis_breakdown)):
      $max_bc = max(array_column($dis_breakdown,'c')); ?>
    <div class="barchart">
      <div class="bc-head">
        <span class="bc-title">📊 Disease Frequency Breakdown</span>
        <span class="chip chip-g">Top <?= count($dis_breakdown) ?></span>
      </div>
      <?php foreach ($dis_breakdown as $bcr):
        $bp2 = $max_bc > 0 ? (int)round(($bcr['c']/$max_bc)*100) : 0; ?>
      <div class="bc-row">
        <div class="bc-lbl"><?= safeHtml($bcr['disease_name']) ?></div>
        <div class="bc-track"><div class="bc-fill" style="width:<?= $bp2 ?>%"></div></div>
        <div class="bc-num"><?= $bcr['c'] ?></div>
      </div>
      <?php endforeach; ?>
    </div>
    <?php endif; ?>


<?php /* ═══════════════════════════════════════════════════════════════════════
         SECTION ▸ ADVANCED LOGS
   ═══════════════════════════════════════════════════════════════════════ */
elseif ($sec === 'logs'): ?>

    <div class="hero hero-blue">
      <div class="hero-pill">📋 Detection Logs</div>
      <h2>Advanced Disease Detection Logs</h2>
      <p>Search, filter and sort every detection record &nbsp;·&nbsp; Full export available</p>
    </div>

    <div class="panel">
      <div class="panel-head">
        <div class="panel-title">
          🔍 Search &amp; Filter
          <span class="panel-sub">
            Showing <strong><?= count($log_recs) ?></strong> of <strong><?= $log_total ?></strong>
            <?php if ($fq||$fstat||$fplant||$fuser||$fdfrom||$fdto): ?>
            &nbsp;<span style="color:var(--b600);font-weight:700">· Filters active</span>
            <?php endif; ?>
          </span>
        </div>
      </div>

      <!-- Filter row -->
      <div class="fzone">
        <form method="GET" action="">
          <input type="hidden" name="section" value="logs">
          <div class="frow">
            <!-- Search -->
            <div class="fg">
              <label>Search</label>
              <input type="search" class="finput" name="q" value="<?= safeHtml($fq) ?>" placeholder="User, plant, disease…">
            </div>
            <!-- Status -->
            <?php if ($has_stat): ?>
            <div class="fg">
              <label>Status</label>
              <select name="fstat" class="fsel">
                <option value="">All Statuses</option>
                <option value="detected"    <?= $fstat==='detected'   ?'selected':'' ?>>🔴 Detected</option>
                <option value="in_progress" <?= $fstat==='in_progress'?'selected':'' ?>>🔵 In Progress</option>
                <option value="recovered"   <?= $fstat==='recovered'  ?'selected':'' ?>>🟢 Recovered</option>
              </select>
            </div>
            <?php endif; ?>
            <!-- Plant -->
            <?php if ($has_plant && !empty($plant_opts)): ?>
            <div class="fg">
              <label>Plant</label>
              <select name="fplant" class="fsel">
                <option value="">All Plants</option>
                <?php foreach ($plant_opts as $po): ?>
                <option value="<?= safeHtml($po) ?>" <?= $fplant===$po?'selected':'' ?>><?= safeHtml($po) ?></option>
                <?php endforeach; ?>
              </select>
            </div>
            <?php endif; ?>
            <!-- User -->
            <?php if (!empty($user_opts)): ?>
            <div class="fg">
              <label>User</label>
              <select name="fuser" class="fsel">
                <option value="">All Users</option>
                <?php foreach ($user_opts as $uo): ?>
                <option value="<?= safeHtml($uo) ?>" <?= $fuser===$uo?'selected':'' ?>><?= safeHtml($uo) ?></option>
                <?php endforeach; ?>
              </select>
            </div>
            <?php endif; ?>
            <!-- Date range -->
            <div class="fg">
              <label>Date From</label>
              <input type="date" class="finput fsel" name="dfrom" value="<?= safeHtml($fdfrom) ?>">
            </div>
            <div class="fg">
              <label>Date To</label>
              <input type="date" class="finput fsel" name="dto" value="<?= safeHtml($fdto) ?>">
            </div>
            <!-- Sort -->
            <div class="fg">
              <label>Sort By</label>
              <select name="sort" class="fsel">
                <option value="latest"   <?= $fsort==='latest'  ?'selected':'' ?>>Latest First</option>
                <option value="disease"  <?= $fsort==='disease' ?'selected':'' ?>>Disease Name</option>
                <option value="recovery" <?= $fsort==='recovery'?'selected':'' ?>>Recovery Progress</option>
              </select>
            </div>
            <button type="submit" class="fbtn">Apply</button>
            <a href="admin.php?section=logs" class="freset">Reset</a>
          </div>
        </form>
      </div>

      <!-- Meta + export -->
      <div class="meta-bar">
        <span style="font-weight:600;color:var(--gr700)"><?= count($log_recs) ?> records displayed</span>
        <div class="exp-bar no-print">
          <a href="admin.php?export=csv" class="expbtn exp-csv" target="_blank">⬇ CSV</a>
          <button class="expbtn exp-pdf" onclick="window.print()">🖨 PDF</button>
          <button class="expbtn exp-print" onclick="window.print()">🖨 Print</button>
        </div>
      </div>

      <!-- Table -->
      <div class="t-wrap">
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>User</th>
              <?php if ($has_plant): ?><th>Plant</th><?php endif; ?>
              <th>Disease Detected</th>
              <?php if ($has_conf): ?><th>Confidence</th><?php endif; ?>
              <th>Status</th>
              <th>Detection Date</th>
              <?php if ($has_days): ?><th>Recovery Est.</th><?php endif; ?>
              <th class="no-print">Action</th>
            </tr>
          </thead>
          <tbody>
          <?php if (empty($log_recs)): ?>
            <tr><td colspan="10">
              <div class="empty-box">
                <div class="empty-box-ico">📭</div>
                <p>No records match your filters.</p>
              </div>
            </td></tr>
          <?php else: foreach ($log_recs as $lr): ?>
            <tr>
              <td style="color:var(--gr400);font-weight:700;font-size:12px"><?= (int)$lr['id'] ?></td>
              <td>
                <div style="font-weight:700;font-size:12.5px"><?= safeHtml($lr['user_name']) ?></div>
                <div style="font-size:11px;color:var(--gr400)"><?= safeHtml($lr['user_email']) ?></div>
              </td>
              <?php if ($has_plant): ?>
              <td>
                <?php if ($lr['plant_name']): ?>
                <span style="display:inline-flex;align-items:center;gap:4px;font-weight:600;font-size:12px">
                  🌿 <?= safeHtml($lr['plant_name']) ?>
                </span>
                <?php else: ?>
                <span style="color:var(--gr300)">—</span>
                <?php endif; ?>
              </td>
              <?php endif; ?>
              <td style="font-weight:600;font-size:12.5px;max-width:220px;word-break:break-word"><?= safeHtml($lr['disease_name']) ?></td>
              <?php if ($has_conf): ?>
              <td>
                <?php if ((float)$lr['confidence'] > 0):
                  $cv = (float)$lr['confidence'];
                  // Feature 2: bar turns green when plant is fully recovered
                  $cf_cls = ($lr['status'] === 'recovered') ? 'cf-high'
                           : ($cv >= 80 ? 'cf-high' : ($cv >= 50 ? 'cf-mid' : 'cf-low')); ?>
                <div class="conf-bar">
                  <div class="conf-track"><div class="conf-fill <?= $cf_cls ?>" style="width:<?= min(100,(int)$cv) ?>%"></div></div>
                  <span style="font-weight:700;font-size:12px"><?= $cv ?>%</span>
                </div>
                <?php else: ?><span style="color:var(--gr300)">—</span><?php endif; ?>
              </td>
              <?php endif; ?>
              <td>
                <?php
                  $st = $lr['status'];
                  if ($st === 'recovered') {
                    $rci_cls = 'rci-recovered'; $rci_dot = '#22c55e'; $rci_bar = 'rci-fill-rec'; $rci_pct = 100; $rci_lbl = '🟢 Recovered';
                  } elseif ($st === 'in_progress') {
                    $rci_cls = 'rci-progress';  $rci_dot = '#f97316'; $rci_bar = 'rci-fill-prog'; $rci_pct = 55;  $rci_lbl = '🟠 In Progress';
                  } else {
                    $rci_cls = 'rci-detected';  $rci_dot = '#ef4444'; $rci_bar = 'rci-fill-det';  $rci_pct = 15;  $rci_lbl = '🔴 Detected';
                  }
                ?>
                <div class="rci-wrap">
                  <span class="rci-badge <?= $rci_cls ?>">
                    <span class="rci-dot" style="background:<?= $rci_dot ?>"></span>
                    <?= $rci_lbl ?>
                  </span>
                  <div class="rci-bar">
                    <div class="rci-bar-fill <?= $rci_bar ?>" style="width:<?= $rci_pct ?>%"></div>
                  </div>
                </div>
              </td>
              <td style="white-space:nowrap">
                <div style="font-size:12px;font-weight:600"><?= date('M j, Y', strtotime($lr['scanned_at'])) ?></div>
                <div style="font-size:11px;color:var(--gr400)"><?= date('g:i A', strtotime($lr['scanned_at'])) ?></div>
              </td>
              <?php if ($has_days): ?>
              <td style="font-weight:600;font-size:12.5px">
                <?= (isset($lr['estimated_days'])&&$lr['estimated_days']>0) ? $lr['estimated_days'].' days' : '<span style="color:var(--gr300)">—</span>' ?>
              </td>
              <?php endif; ?>
              <td class="no-print">
                <a href="http://localhost:5000/treatment_log?record_id=<?= (int)$lr['id'] ?>"
                   class="tbtn"
                   style="background:var(--g50);color:var(--g700);border:1px solid var(--g200);margin-bottom:4px;display:inline-block;"
                   title="View Treatment Log">📋 Log</a>
                <a href="admin.php?del=<?= (int)$lr['id'] ?>&section=logs<?= $fq||$fstat||$fplant||$fuser||$fdfrom||$fdto ? '&q='.urlencode($fq).'&fstat='.urlencode($fstat).'&fplant='.urlencode($fplant).'&fuser='.urlencode($fuser).'&dfrom='.urlencode($fdfrom).'&dto='.urlencode($fdto) : '' ?>"
                   class="tbtn tbtn-del"
                   onclick="return confirm('Delete this detection record?')">Delete</a>
              </td>
            </tr>
          <?php endforeach; endif; ?>
          </tbody>
        </table>
      </div>
    </div>


<?php /* ═══════════════════════════════════════════════════════════════════════
         SECTION ▸ REPORTS
   ═══════════════════════════════════════════════════════════════════════ */
elseif ($sec === 'reports'): ?>

    <div class="hero hero-orange">
      <div class="hero-pill">📅 Reporting System</div>
      <h2>Daily &amp; Monthly Analytics Reports</h2>
      <p>Summary snapshots for operational review and performance tracking</p>
    </div>

    <!-- Report cards -->
    <div class="rep-grid">
      <!-- Daily -->
      <div class="rep-card">
        <div class="rep-head">
          <div class="rep-head-ico" style="background:#fff7ed">📅</div>
          <div>
            <div class="rep-head-title">Daily Report</div>
            <div class="rep-head-sub"><?= date('l, F j, Y') ?></div>
          </div>
        </div>
        <div class="rep-body">
          <div class="rstat">
            <div class="rstat-val"><?= $today_scans ?></div>
            <div class="rstat-lbl">Total Scans Today</div>
          </div>
          <div class="rstat">
            <div class="rstat-val"><?= $today_active ?></div>
            <div class="rstat-lbl">Active Cases</div>
          </div>
          <div class="rstat">
            <div class="rstat-val"><?= $today_done ?></div>
            <div class="rstat-lbl">Completed Today</div>
          </div>
          <div class="rstat rstat-full">
            <div class="rstat-lbl" style="margin-bottom:4px">Most Detected Disease Today</div>
            <div style="font-size:15px;font-weight:800;color:var(--gr900)"><?= safeHtml($today_top_dis) ?></div>
          </div>
        </div>
      </div>

      <!-- Monthly -->
      <div class="rep-card">
        <div class="rep-head">
          <div class="rep-head-ico" style="background:#eff6ff">📆</div>
          <div>
            <div class="rep-head-title">Monthly Report</div>
            <div class="rep-head-sub"><?= date('F Y') ?></div>
          </div>
        </div>
        <div class="rep-body">
          <div class="rstat">
            <div class="rstat-val"><?= $month_scans ?></div>
            <div class="rstat-lbl">Scans This Month</div>
          </div>
          <div class="rstat">
            <div class="rstat-val"><?= $month_rec_rate ?>%</div>
            <div class="rstat-lbl">Recovery Rate</div>
            <div class="pbar"><div class="pbar-fill pf-green" style="width:<?= $month_rec_rate ?>%"></div></div>
          </div>
          <div class="rstat">
            <div class="rstat-lbl" style="margin-bottom:4px">Most Affected Plant</div>
            <div style="font-size:14px;font-weight:800;color:var(--gr900)"><?= safeHtml($month_top_plant) ?></div>
          </div>
          <div class="rstat">
            <div class="rstat-lbl" style="margin-bottom:4px">Most Common Disease</div>
            <div style="font-size:14px;font-weight:800;color:var(--gr900)"><?= safeHtml($month_top_dis) ?></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Export hub -->
    <div class="panel">
      <div class="panel-head">
        <div class="panel-title">📤 Export &amp; Download Options</div>
        <span style="font-size:11px;color:var(--gr400)">Exports include: System name · Report date · Admin name · All data</span>
      </div>
      <div style="padding:22px;display:flex;gap:12px;flex-wrap:wrap;align-items:center">
        <a href="admin.php?export=csv" target="_blank" class="expbtn exp-csv" style="padding:10px 20px;font-size:13px">
          ⬇ Export Full System CSV
        </a>
        <button class="expbtn exp-pdf" style="padding:10px 20px;font-size:13px" onclick="window.print()">
          🖨 Save Full Report as PDF
        </button>
        <button class="expbtn exp-print" style="padding:10px 20px;font-size:13px" onclick="window.print()">
          🖨 Print Full System Report
        </button>
        <p style="font-size:12px;color:var(--gr400);margin-left:4px">
          CSV includes all records &nbsp;·&nbsp; PDF uses browser print dialog (Save as PDF)
        </p>
      </div>
    </div>

    <!-- Per-user report -->
    <div class="panel">
      <div class="panel-head">
        <div class="panel-title">👤 Individual User Reports</div>
        <span style="font-size:11px;color:var(--gr400)">Select a user to preview, print or export their records only</span>
      </div>
      <div class="t-wrap">
        <table>
          <thead>
            <tr><th>#</th><th>Name</th><th>Email</th><th>Scans</th><th class="no-print">Actions</th></tr>
          </thead>
          <tbody>
          <?php foreach ($all_users as $u):
            $uid_key = (int)$u['id'];
            $scan_count = 0;
            // Simple inline count approach
            try {
              $sc_stmt = $pdo->prepare("SELECT COUNT(*) FROM disease_records WHERE user_id=?");
              $sc_stmt->execute([$uid_key]);
              $scan_count = (int)$sc_stmt->fetchColumn();
            } catch(PDOException $e){ $scan_count = 0; }
          ?>
            <tr>
              <td style="color:var(--gr400);font-weight:600"><?= $uid_key ?></td>
              <td style="font-weight:700"><?= safeHtml($u['name']) ?></td>
              <td style="color:var(--gr500)"><?= safeHtml($u['email']) ?></td>
              <td><span class="chip chip-b"><?= $scan_count ?> scans</span></td>
              <td class="no-print" style="white-space:nowrap">
                <!-- <button class="tbtn" style="background:#eff6ff;color:#1d4ed8"
                  onclick="openUserReport(<?= $uid_key ?>, <?= json_encode($u['name']) ?>, <?= json_encode($u['email']) ?>)">
                  📋 Preview &amp; Print
                </button> -->
                <button class="tbtn" style="background:#eff6ff;color:#1d4ed8"
    onclick="openUserReport('<?= $uid_key ?>', <?= htmlspecialchars(json_encode($u['name']), ENT_QUOTES) ?>, <?= htmlspecialchars(json_encode($u['email']), ENT_QUOTES) ?>)">
    📋 Preview &amp; Print
</button>
                <a href="admin.php?export=user_csv&uid=<?= $uid_key ?>" target="_blank"
                   class="tbtn" style="background:#dcfce7;color:#15803d">
                  ⬇ Download CSV
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
          <?php if (empty($all_users)): ?>
            <tr><td colspan="5"><div class="empty-box"><div class="empty-box-ico">👥</div><p>No users yet.</p></div></td></tr>
          <?php endif; ?>
          </tbody>
        </table>
      </div>
    </div>

    <!-- All-time summary printable -->
    <div class="panel">
      <div class="panel-head">
        <div class="panel-title">📊 All-Time Platform Summary</div>
        <button class="expbtn exp-print no-print" onclick="window.print()">🖨 Print</button>
      </div>
      <div style="padding:20px;display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px">
        <?php
        $sumstats = [
          ['👥','Total Users',     $ttl_users,     '#eff6ff'],
          ['🔬','Total Scans',     $ttl_recs,      '#f0fdf4'],
          ['💊','In Treatment',    $ttl_active,    '#fefce8'],
          ['✅','Recovered',       $ttl_recovered, '#dcfce7'],
          ['📈','Recovery Rate',   $rec_rate.'%',  '#dcfce7'],
          ['📅','Scans Today',     $today_scans,   '#faf5ff'],
          ['📆','Scans This Month',$month_scans,   '#eff6ff'],
          ['📊','30-Day Growth',   ($growth_pct>=0?'+':'').$growth_pct.'%', '#fff7ed'],
        ];
        foreach ($sumstats as [$ico,$lbl,$val,$bg]): ?>
        <div style="background:<?= $bg ?>;border-radius:10px;padding:14px 15px">
          <div style="font-size:20px;margin-bottom:6px"><?= $ico ?></div>
          <div style="font-size:22px;font-weight:800;letter-spacing:-.5px;color:var(--gr900)"><?= safeHtml((string)$val) ?></div>
          <div style="font-size:11px;font-weight:600;color:var(--gr500);margin-top:2px"><?= $lbl ?></div>
        </div>
        <?php endforeach; ?>
      </div>
    </div>


<?php /* ═══════════════════════════════════════════════════════════════════════
         SECTION ▸ SYSTEM INSIGHTS
   ═══════════════════════════════════════════════════════════════════════ */
elseif ($sec === 'insights'): ?>

    <div class="hero hero-purple">
      <div class="hero-pill">⚡ Intelligence Engine</div>
      <h2>Real-Time System Insights</h2>
      <p>Automated pattern detection &nbsp;·&nbsp; Urgent alerts &nbsp;·&nbsp; Growth analytics</p>
    </div>

    <!-- Quick metrics -->
    <div class="card-grid">
      <div class="card" style="border-top:3px solid var(--r500)">
        <div class="card-ico" style="background:var(--r50)">🚨</div>
        <div class="card-val"><?= count($urgent_cases) ?></div>
        <div class="card-lbl">Urgent Cases</div>
        <div class="card-sub">In-progress &gt;7 days</div>
        <?php if (count($urgent_cases) > 0): ?><div class="card-badge cb-dn">Attention</div><?php endif; ?>
      </div>
      <div class="card" style="border-top:3px solid var(--y500)">
        <div class="card-ico" style="background:var(--y50)">🔁</div>
        <div class="card-val"><?= count($repeat_inf) ?></div>
        <div class="card-lbl">Repeat Infections</div>
        <div class="card-sub">Same user + disease</div>
      </div>
      <div class="card" style="border-top:3px solid var(--b500)">
        <div class="card-ico" style="background:var(--b50)">⚡</div>
        <div class="card-val" style="font-size:18px;letter-spacing:-.3px"><?= safeHtml((string)$most_active['name']) ?></div>
        <div class="card-lbl">Most Active User</div>
        <div class="card-sub"><?= (int)$most_active['scans'] ?> total scans</div>
      </div>
      <div class="card c-growth">
        <div class="card-ico">📊</div>
        <div class="card-val"><?= $growth_pct >= 0 ? '+'.$growth_pct : $growth_pct ?>%</div>
        <div class="card-lbl">30-Day Growth</div>
        <div class="card-sub">Platform scan volume</div>
        <div class="pbar" style="margin-top:8px">
          <div class="pbar-fill pf-blue" style="width:<?= min(100,abs($growth_pct)) ?>%"></div>
        </div>
      </div>
    </div>

    <!-- 2×2 insight panels -->
    <div class="ins-grid">

      <!-- 1. Urgent attention -->
      <div class="ins-card">
        <div class="ins-head" style="background:#fef2f2;border-bottom-color:#fecaca">
          <span style="font-size:16px">🚨</span>
          <div class="ins-head-lbl" style="color:var(--r700)">Plants Needing Urgent Attention</div>
          <span class="ins-head-cnt ib-r"><?= count($urgent_cases) ?> cases</span>
        </div>
        <?php if (empty($urgent_cases)): ?>
        <div class="empty-box" style="padding:30px 20px">
          <div class="empty-box-ico">✅</div><p>No urgent cases — everything looks healthy!</p>
        </div>
        <?php else: foreach ($urgent_cases as $uc): ?>
        <div class="ins-item">
          <div class="ins-ico" style="background:#fef2f2">🌿</div>
          <div class="ins-body">
            <div class="ins-main"><?= safeHtml($uc['plant_name'] ?: 'Unknown Plant') ?> — <?= safeHtml($uc['disease_name']) ?></div>
            <div class="ins-sub">👤 <?= safeHtml($uc['user_name']) ?> &nbsp;·&nbsp; Since <?= date('M j', strtotime($uc['scanned_at'])) ?></div>
            <div class="pbar"><div class="pbar-fill pf-red" style="width:<?= min(100,(int)min($uc['days_ago'],30)/30*100) ?>%"></div></div>
          </div>
          <span class="ins-badge ib-r"><?= (int)$uc['days_ago'] ?>d</span>
        </div>
        <?php endforeach; endif; ?>
      </div>

      <!-- 2. Repeat infections -->
      <div class="ins-card">
        <div class="ins-head" style="background:#fff7ed;border-bottom-color:#fed7aa">
          <span style="font-size:16px">🔁</span>
          <div class="ins-head-lbl" style="color:var(--o700)">Repeated Infections</div>
          <span class="ins-head-cnt ib-o"><?= count($repeat_inf) ?> patterns</span>
        </div>
        <?php if (empty($repeat_inf)): ?>
        <div class="empty-box" style="padding:30px 20px">
          <div class="empty-box-ico">👍</div><p>No repeat infection patterns found.</p>
        </div>
        <?php else: foreach ($repeat_inf as $ri): ?>
        <div class="ins-item">
          <div class="ins-ico" style="background:#fff7ed">🦠</div>
          <div class="ins-body">
            <div class="ins-main"><?= safeHtml($ri['disease_name']) ?></div>
            <div class="ins-sub">👤 <?= safeHtml($ri['user_name']) ?></div>
          </div>
          <span class="ins-badge ib-o"><?= (int)$ri['cnt'] ?>× recurrence</span>
        </div>
        <?php endforeach; endif; ?>
      </div>

      <!-- 3. Most active users -->
      <div class="ins-card">
        <div class="ins-head" style="background:#eff6ff;border-bottom-color:#bfdbfe">
          <span style="font-size:16px">⚡</span>
          <div class="ins-head-lbl" style="color:var(--b700)">Most Active Users</div>
          <span class="ins-head-cnt ib-b">Top <?= count($top_users) ?></span>
        </div>
        <?php
        $max_scans = !empty($top_users) ? max(array_column($top_users,'scans')) : 1;
        foreach ($top_users as $i => $tu): ?>
        <div class="ins-item">
          <div class="ins-ico" style="background:#eff6ff;color:var(--b600);font-weight:800;font-size:12px">#<?= $i+1 ?></div>
          <div class="ins-body">
            <div class="ins-main"><?= safeHtml($tu['name']) ?></div>
            <div class="ins-sub"><?= safeHtml($tu['email']) ?></div>
            <div class="pbar">
              <div class="pbar-fill pf-blue" style="width:<?= $max_scans>0?(int)round(($tu['scans']/$max_scans)*100):0 ?>%"></div>
            </div>
          </div>
          <span class="ins-badge ib-b"><?= (int)$tu['scans'] ?> scans</span>
        </div>
        <?php endforeach;
        if (empty($top_users)): ?>
        <div class="empty-box" style="padding:30px 20px"><div class="empty-box-ico">👥</div><p>No scan data yet.</p></div>
        <?php endif; ?>
      </div>

      <!-- 4. Platform health -->
      <div class="ins-card">
        <div class="ins-head" style="background:#f0fdf4;border-bottom-color:#bbf7d0">
          <span style="font-size:16px">📊</span>
          <div class="ins-head-lbl" style="color:var(--g700)">Platform Health</div>
        </div>
        <?php
        $health_rows = [
          ['Platform Growth (30d)', ($growth_pct>=0?'+'.$growth_pct.'%':$growth_pct.'%'), $growth_pct>=0?'ib-g':'ib-r', '📈'],
          ['All-Time Recovery Rate', $rec_rate.'%', $rec_rate>=60?'ib-g':($rec_rate>=30?'ib-o':'ib-r'), '✅'],
          ['Today\'s Scans', $today_scans.' scans', 'ib-b', '📅'],
          ['Month Scans', $month_scans.' scans', 'ib-b', '📆'],
          ['Month Recovery Rate', $month_rec_rate.'%', $month_rec_rate>=60?'ib-g':($month_rec_rate>=30?'ib-o':'ib-r'), '🌿'],
          ['Urgent Open Cases', count($urgent_cases).' cases', count($urgent_cases)>0?'ib-r':'ib-g', '🚨'],
          ['Repeat Infection Users', count($repeat_inf).' patterns', count($repeat_inf)>0?'ib-o':'ib-g', '🔁'],
          ['Most Active User', safeHtml((string)$most_active['name']), 'ib-p', '⚡'],
        ];
        foreach ($health_rows as [$lbl,$val,$cls,$ico]): ?>
        <div class="ins-item">
          <div class="ins-ico" style="background:var(--g50)"><?= $ico ?></div>
          <div class="ins-body"><div class="ins-main"><?= $lbl ?></div></div>
          <span class="ins-badge <?= $cls ?>"><?= $val ?></span>
        </div>
        <?php endforeach; ?>
      </div>

    </div><!-- /ins-grid -->


<?php /* ═══════════════════════════════════════════════════════════════════════
         SECTION ▸ USERS
   ═══════════════════════════════════════════════════════════════════════ */
elseif ($sec === 'users'): ?>

    <div class="panel">
      <div class="panel-head">
        <div class="panel-title">👥 Registered Users</div>
        <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">
          <span class="chip chip-g"><?= count($all_users) ?> total</span>
          <button class="expbtn exp-print no-print" onclick="printFullReport()">🖨 Print Full System Report</button>
          <a href="admin.php?export=csv" target="_blank" class="expbtn exp-csv no-print">⬇ Full CSV Export</a>
        </div>
      </div>
      <div class="t-wrap">
        <table>
          <thead>
            <tr><th>#</th><th>Name</th><th>Email</th><th>Role</th><th>Joined</th><th class="no-print">Actions</th></tr>
          </thead>
          <tbody>
          <?php foreach ($all_users as $u): ?>
            <tr>
              <td style="color:var(--gr400);font-weight:600"><?= (int)$u['id'] ?></td>
              <td style="font-weight:700"><?= safeHtml($u['name']) ?></td>
              <td style="color:var(--gr500)"><?= safeHtml($u['email']) ?></td>
              <td><span class="chip chip-g" style="font-size:11px"><?= ucfirst($u['role']) ?></span></td>
              <td style="font-size:12px"><?= date('M j, Y', strtotime($u['created_at'])) ?></td>
              <td class="no-print">
                <!-- <button class="tbtn" style="background:#eff6ff;color:#1d4ed8"
                  onclick="openUserReport(<?= (int)$u['id'] ?>, <?= json_encode($u['name']) ?>, <?= json_encode($u['email']) ?>)">
                  📋 Print Report
                </button>Version 1 -->
                <button class="tbtn" style="background:#eff6ff;color:#1d4ed8"
  onclick="openUserReport(<?= (int)$u['id'] ?>, '<?= addslashes($u['name']) ?>', '<?= addslashes($u['email']) ?>')">
  📋 Print Report
</button>

                <a href="admin.php?export=user_csv&uid=<?= (int)$u['id'] ?>" target="_blank"
                   class="tbtn" style="background:#dcfce7;color:#15803d">
                  ⬇ CSV
                </a>
                <a href="admin.php?clr=<?= (int)$u['id'] ?>&section=users"
                   class="tbtn tbtn-clr"
                   onclick="return confirm('Clear all scan records for <?= safeHtml($u['name']) ?>?')">
                  Clear Records
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
          <?php if (empty($all_users)): ?>
            <tr><td colspan="6"><div class="empty-box"><div class="empty-box-ico">👥</div><p>No users yet.</p></div></td></tr>
          <?php endif; ?>
          </tbody>
        </table>
      </div>
    </div>

<?php endif; ?>

<?php /* ═══════════════════════════════════════════════════════════════════════
         SECTION ▸ MEDICINE ORDERS
   ═══════════════════════════════════════════════════════════════════════ */
if ($sec === 'orders'): ?>

    <div class="hero hero-orange">
      <div class="hero-pill">🛒 Medicine Store</div>
      <h2>Medicine Orders Management</h2>
      <p>View, manage and update all farmer medicine orders &nbsp;·&nbsp; <?= date('l, F j, Y') ?></p>
    </div>

    <?php if (!$orders_exist): ?>
    <div style="text-align:center;padding:60px 20px;background:white;border-radius:16px;border:1px solid var(--gr200);">
      <div style="font-size:52px;margin-bottom:14px;">⚠️</div>
      <div style="font-size:18px;font-weight:800;margin-bottom:8px;">Orders Table Not Found</div>
      <div style="font-size:14px;color:var(--gr500);margin-bottom:20px;">Please run <strong>create_orders_table.sql</strong> in phpMyAdmin first.</div>
      <code style="background:var(--gr100);padding:10px 18px;border-radius:8px;font-size:13px;">SOURCE create_orders_table.sql</code>
    </div>
    <?php else: ?>

    <!-- ── Stat cards ── -->
    <div class="card-grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:22px;">
      <div class="card" style="border-top:3px solid var(--o500);">
        <div class="card-ico" style="background:var(--o50);">🛒</div>
        <div class="card-val"><?= $ttl_orders ?></div>
        <div class="card-lbl">Total Orders</div>
        <div class="card-sub">All time</div>
      </div>
      <div class="card" style="border-top:3px solid var(--y500);">
        <div class="card-ico" style="background:var(--y50);">⏳</div>
        <div class="card-val" style="color:<?= $ttl_pending>0?'var(--o700)':'var(--gr900)' ?>"><?= $ttl_pending ?></div>
        <div class="card-lbl">Pending</div>
        <div class="card-sub">Needs action</div>
      </div>
      <div class="card" style="border-top:3px solid var(--g500);">
        <div class="card-ico" style="background:var(--g50);">💰</div>
        <div class="card-val">$<?= number_format($ttl_revenue, 2) ?></div>
        <div class="card-lbl">Total Revenue</div>
        <div class="card-sub">Excl. cancelled</div>
      </div>
      <div class="card" style="border-top:3px solid var(--b500);">
        <div class="card-ico" style="background:var(--b50);">📅</div>
        <div class="card-val"><?= $orders_today ?></div>
        <div class="card-lbl">Today's Orders</div>
        <div class="card-sub"><?= date('M j, Y') ?></div>
      </div>
    </div>

    <!-- ── Filter bar ── -->
    <form method="GET" action="admin.php" style="display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:18px;">
      <input type="hidden" name="section" value="orders">
      <input type="text" name="ord_q" value="<?= safeHtml($ord_q ?? '') ?>"
             placeholder="🔍 Search name or email…"
             style="flex:1;min-width:180px;padding:9px 14px;border:1.5px solid var(--gr300);border-radius:9px;font-family:inherit;font-size:13px;outline:none;">
      <select name="ord_fstat" style="padding:9px 12px;border:1.5px solid var(--gr300);border-radius:9px;font-family:inherit;font-size:13px;color:var(--gr700);background:white;outline:none;">
        <option value="">All Statuses</option>
        <option value="pending"   <?= ($ord_fstat??'')==='pending'   ?'selected':'' ?>>⏳ Pending</option>
        <option value="confirmed" <?= ($ord_fstat??'')==='confirmed' ?'selected':'' ?>>✅ Confirmed</option>
        <option value="shipped"   <?= ($ord_fstat??'')==='shipped'   ?'selected':'' ?>>🚚 Shipped</option>
        <option value="delivered" <?= ($ord_fstat??'')==='delivered' ?'selected':'' ?>>📦 Delivered</option>
        <option value="cancelled" <?= ($ord_fstat??'')==='cancelled' ?'selected':'' ?>>❌ Cancelled</option>
      </select>
      <button type="submit" style="padding:9px 18px;border:none;border-radius:9px;background:var(--o700);color:white;font-family:inherit;font-size:13px;font-weight:700;cursor:pointer;">Filter</button>
      <a href="admin.php?section=orders" style="padding:9px 14px;border:1.5px solid var(--gr300);border-radius:9px;font-size:13px;color:var(--gr600);font-weight:600;">Clear</a>
    </form>

    <!-- ── Orders table ── -->
    <div class="t-wrap">
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Order ID</th>
            <th>Farmer / User</th>
            <th>Email</th>
            <th>Items</th>
            <th>Total</th>
            <th>Status</th>
            <th>Ordered At</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <?php if (empty($all_orders)): ?>
          <tr><td colspan="9">
            <div class="empty-box">
              <div class="empty-box-ico">🛒</div>
              <p>No orders yet. Orders will appear here when farmers buy medicine.</p>
            </div>
          </td></tr>
        <?php else: ?>
        <?php foreach ($all_orders as $i => $ord):
            $st = $ord['status'];
            $st_style = match($st) {
                'pending'   => 'background:#fef3c7;color:#92400e;border:1px solid #fde68a',
                'confirmed' => 'background:#dbeafe;color:#1e40af;border:1px solid #bfdbfe',
                'shipped'   => 'background:#ede9fe;color:#6d28d9;border:1px solid #ddd6fe',
                'delivered' => 'background:#dcfce7;color:#166534;border:1px solid #bbf7d0',
                'cancelled' => 'background:#fee2e2;color:#991b1b;border:1px solid #fecaca',
                default     => 'background:var(--gr100);color:var(--gr700)',
            };
            $st_icon = match($st) {
                'pending'=>'⏳','confirmed'=>'✅','shipped'=>'🚚','delivered'=>'📦','cancelled'=>'❌',default=>'•'
            };
            $oid = (int)$ord['id'];
        ?>
          <tr>
            <td style="color:var(--gr400);font-weight:700"><?= $i+1 ?></td>
            <td style="font-weight:800;color:var(--o700)">#<?= $oid ?></td>
            <td style="font-weight:700"><?= safeHtml($ord['user_name']) ?></td>
            <td style="font-size:12px;color:var(--gr500)"><?= safeHtml($ord['user_email']) ?></td>
            <td style="font-weight:700;text-align:center"><?= (int)$ord['item_count'] ?></td>
            <td style="font-weight:800;color:var(--g700)">$<?= number_format((float)$ord['total_price'],2) ?></td>
            <td>
              <span style="display:inline-flex;align-items:center;gap:5px;padding:4px 10px;border-radius:20px;font-size:11px;font-weight:700;<?= $st_style ?>">
                <?= $st_icon ?> <?= ucfirst($st) ?>
              </span>
            </td>
            <td style="font-size:12px;white-space:nowrap"><?= safeHtml(date('M j, Y g:i A', strtotime($ord['ordered_at']))) ?></td>
            <td>
              <div style="display:flex;gap:5px;flex-wrap:wrap;">
                <!-- View items button -->
                <button class="tbtn" style="background:var(--b50);color:var(--b700)"
                  onclick="viewOrderItems(<?= $oid ?>)">📦 Items</button>
                <!-- Status update dropdown -->
                <select onchange="if(this.value)window.location='admin.php?section=orders&oid=<?= $oid ?>&order_status='+this.value"
                  style="padding:4px 8px;border:1.5px solid var(--gr300);border-radius:7px;font-family:inherit;font-size:12px;color:var(--gr700);background:white;cursor:pointer;outline:none;">
                  <option value="">✏️ Change Status</option>
                  <option value="pending">⏳ Pending</option>
                  <option value="confirmed">✅ Confirmed</option>
                  <option value="shipped">🚚 Shipped</option>
                  <option value="delivered">📦 Delivered</option>
                  <option value="cancelled">❌ Cancel</option>
                </select>
              </div>
            </td>
          </tr>
        <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
      </table>
    </div>

    <!-- ── Order Items Modal ── -->
    <div id="orderModalBg" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,0.5);z-index:500;align-items:center;justify-content:center;">
      <div style="background:white;border-radius:18px;width:90%;max-width:640px;max-height:80vh;display:flex;flex-direction:column;box-shadow:0 24px 64px rgba(0,0,0,0.18);">
        <div style="padding:20px 24px 16px;border-bottom:1px solid var(--gr100);display:flex;align-items:center;justify-content:space-between;">
          <div>
            <div style="font-size:17px;font-weight:800;" id="omodTitle">Order Items</div>
            <div style="font-size:12px;color:var(--gr500);" id="omodSub"></div>
          </div>
          <button onclick="closeOrderModal()" style="border:none;background:var(--gr100);border-radius:8px;padding:6px 10px;cursor:pointer;font-size:14px;">✕</button>
        </div>
        <div style="flex:1;overflow-y:auto;padding:20px 24px;" id="omodBody"></div>
      </div>
    </div>

    <!-- Embed order items as JSON for JS modal -->
    <script id="orderItemsData" type="application/json"><?= json_encode($order_items_map, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP) ?></script>

    <script>
    (function(){
        var itemsMap = {};
        try { itemsMap = JSON.parse(document.getElementById('orderItemsData').textContent); } catch(e){}

        window.viewOrderItems = function(oid) {
            var items = itemsMap[String(oid)] || [];
            document.getElementById('omodTitle').textContent = '📦 Order #' + oid + ' — Items';
            document.getElementById('omodSub').textContent   = items.length + ' item type(s) in this order';

            if (!items.length) {
                document.getElementById('omodBody').innerHTML = '<div style="text-align:center;padding:40px;color:var(--gr400);">No items found for this order.</div>';
            } else {
                var rows = items.map(function(it) {
                    return '<tr>'
                        + '<td style="font-size:14px;font-weight:700">' + esc(it.medicine_name) + '</td>'
                        + '<td><span style="background:var(--o50);color:var(--o700);padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700">' + esc(it.medicine_type) + '</span></td>'
                        + '<td style="font-size:12px;color:var(--gr500)">🌿 ' + esc(it.plant_target) + '</td>'
                        + '<td style="text-align:center;font-weight:700">' + it.quantity + '</td>'
                        + '<td style="color:var(--gr600)">$' + parseFloat(it.unit_price).toFixed(2) + '</td>'
                        + '<td style="font-weight:800;color:var(--g700)">$' + parseFloat(it.line_total).toFixed(2) + '</td>'
                        + '</tr>';
                }).join('');
                document.getElementById('omodBody').innerHTML =
                    '<table style="width:100%;border-collapse:collapse;">'
                    + '<thead><tr style="border-bottom:2px solid var(--gr200);font-size:11px;color:var(--gr500);font-weight:700;text-transform:uppercase;">'
                    + '<th style="padding:8px 6px;text-align:left">Medicine</th>'
                    + '<th style="padding:8px 6px;text-align:left">Type</th>'
                    + '<th style="padding:8px 6px;text-align:left">For Plant</th>'
                    + '<th style="padding:8px 6px;text-align:center">Qty</th>'
                    + '<th style="padding:8px 6px;text-align:left">Unit Price</th>'
                    + '<th style="padding:8px 6px;text-align:left">Total</th>'
                    + '</tr></thead>'
                    + '<tbody>' + rows + '</tbody>'
                    + '</table>';
            }

            var bg = document.getElementById('orderModalBg');
            bg.style.display = 'flex';
        };

        window.closeOrderModal = function() {
            document.getElementById('orderModalBg').style.display = 'none';
        };

        document.getElementById('orderModalBg').addEventListener('click', function(e){
            if (e.target === this) closeOrderModal();
        });

        function esc(s){ return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
    }());
    </script>

    <?php endif; /* orders_exist */ ?>

<?php endif; /* end orders section */ ?>

<?php /* end section switch */ ?>

<!-- ══════════ USER PRINT MODAL ══════════ -->
<div class="pmodal-bg" id="printModalBg">
  <div class="pmodal" id="printModal">
    <div class="pmodal-head">
      <div>
        <div class="pmodal-title" id="pmTitle">User Report</div>
        <div class="pmodal-sub" id="pmSub">Individual detection records</div>
      </div>
      <button class="pmodal-close" onclick="closePrintModal()">✕</button>
    </div>
    <div class="pmodal-body" id="pmBody">
      <!-- filled by JS -->
    </div>
    <div class="pmodal-foot">
      <span style="font-size:12px;color:var(--gr500)" id="pmRecCount"></span>
      <div style="display:flex;gap:8px;flex-wrap:wrap">
        <a id="pmCsvBtn" href="#" class="expbtn exp-csv" target="_blank">⬇ Export CSV</a>
        <button class="expbtn exp-print" onclick="printModal()">🖨 Print / Save PDF</button>
        <button class="expbtn exp-pdf no-print" onclick="closePrintModal()" style="background:var(--gr100);color:var(--gr700)">✕ Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Embed user records map as JSON -->
<script id="urmapData" type="application/json"><?= $user_records_json ?></script>

<script>
(function () {
  // ── Parse embedded data ──────────────────────────────────────────────────────
  window.urmap = {};
  try { window.urmap = JSON.parse(document.getElementById('urmapData').textContent); }
  catch(e) { console.error('urmap parse error', e); }
  var urmap = window.urmap;

  // User list from PHP (for names/emails)
  var allUsers = <?= json_encode(array_map(function($u){ return ['id'=>(int)$u['id'],'name'=>$u['name'],'email'=>$u['email'],'role'=>$u['role']]; }, $all_users)) ?>;

  // ── Helpers ──────────────────────────────────────────────────────────────────
  function esc(s){ return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
  function fmtDate(s){ var d=new Date(s); return isNaN(d)?s:d.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}); }

  function statusInfo(s){
    if (s==='recovered')   return {cls:'rci-recovered', dot:'#22c55e', bar:'rci-fill-rec',  pct:100, label:'🟢 Recovered'};
    if (s==='in_progress') return {cls:'rci-progress',  dot:'#f97316', bar:'rci-fill-prog', pct:55,  label:'🟠 In Progress'};
    return                        {cls:'rci-detected',  dot:'#ef4444', bar:'rci-fill-det',  pct:15,  label:'🔴 Detected'};
  }

  // ── Build report table HTML ───────────────────────────────────────────────────
  function buildReportTable(uid, uname) {
    var recs = urmap[String(uid)] || [];
    if (recs.length === 0) {
      return '<div class="empty-box"><div class="empty-box-ico">📭</div><p>No scan records found for this user.</p></div>';
    }

    var prptHead = '<div class="prpt-head">'
      + '<h2>🌿 BATANOX — Individual User Report</h2>'
      + '<p>User: <strong>' + esc(uname) + '</strong> &nbsp;·&nbsp; Generated <?= date("F j, Y g:i A") ?> &nbsp;·&nbsp; By <?= safeHtml($admin_name) ?></p>'
      + '</div>';

    var rows = recs.map(function(r, i) {
      var si = statusInfo(r.status);
      var confPct = r.confidence > 0 ? r.confidence : 0;
      // When recovered, confidence bar turns green regardless of value
      var confCls = r.status === 'recovered' ? 'cf-high' : (confPct >= 80 ? 'cf-high' : (confPct >= 50 ? 'cf-mid' : 'cf-low'));
      return '<tr>'
        + '<td style="color:var(--gr400);font-weight:700">' + (i+1) + '</td>'
        + '<td>' + (r.plant_name ? '🌿 '+esc(r.plant_name) : '<span style="color:var(--gr300)">—</span>') + '</td>'
        + '<td style="font-weight:600">' + esc(r.disease_name) + '</td>'
        + '<td>'
          + (confPct > 0
            ? '<div class="conf-bar"><div class="conf-track"><div class="conf-fill '+confCls+'" style="width:'+Math.min(100,confPct)+'%"></div></div>'
              + '<span style="font-weight:700;font-size:12px">'+confPct+'%</span></div>'
            : '<span style="color:var(--gr300)">—</span>')
        + '</td>'
        + '<td>'
          + '<div class="rci-wrap">'
          + '<span class="rci-badge '+si.cls+'">'
          + '<span class="rci-dot" style="background:'+si.dot+'"></span>'
          + si.label + '</span>'
          + '<div class="rci-bar"><div class="rci-bar-fill '+si.bar+'" style="width:'+si.pct+'%"></div></div>'
          + '</div>'
        + '</td>'
        + '<td style="font-size:12px">'
          + (r.treatment
            ? '<span style="color:var(--gr700);font-size:11px;line-height:1.4;display:block;max-width:200px">' + esc(r.treatment.substring(0,90)) + (r.treatment.length>90?'…':'') + '</span>'
            : '<span style="color:var(--gr300)">—</span>')
        + '</td>'
        + '<td style="white-space:nowrap;font-size:12px">' + esc(fmtDate(r.scanned_at)) + '</td>'
        + '<td style="font-weight:600">' + (r.estimated_days ? r.estimated_days+' days' : '<span style="color:var(--gr300)">—</span>') + '</td>'
        + '</tr>';
    }).join('');

    return prptHead
      + '<div class="t-wrap">'
      + '<table><thead><tr>'
      + '<th>#</th><th>Plant</th><th>Disease</th><th>Confidence</th>'
      + '<th>Recovery Status</th><th>Treatment</th><th>Date</th><th>Est. Days</th>'
      + '</tr></thead><tbody>' + rows + '</tbody></table>'
      + '</div>';
  }

  // ── Open modal ────────────────────────────────────────────────────────────────
  window.openUserReport = function(uid, uname, uemail) {
    // JSON keys are always strings — convert uid to string for lookup
    var key  = String(uid);
    var recs = urmap[key] || [];
    document.getElementById('pmTitle').textContent    = '📋 User Report — ' + uname;
    document.getElementById('pmSub').textContent      = uemail + '  ·  ' + recs.length + ' records';
    document.getElementById('pmRecCount').textContent = recs.length + ' records total';
    document.getElementById('pmBody').innerHTML       = buildReportTable(key, uname);
    document.getElementById('pmCsvBtn').href          = 'admin.php?export=user_csv&uid=' + uid;
    document.getElementById('printModalBg').classList.add('open');
    document.body.style.overflow = 'hidden';
  };

  window.closePrintModal = function() {
    document.getElementById('printModalBg').classList.remove('open');
    document.body.style.overflow = '';
  };

  window.printModal = function() {
    var bg = document.getElementById('printModalBg');
    bg.classList.add('printing');
    window.print();
    setTimeout(function(){ bg.classList.remove('printing'); }, 500);
  };

  // Close on backdrop click
  document.getElementById('printModalBg').addEventListener('click', function(e){
    if (e.target === this) closePrintModal();
  });

  // ── Build Full System Print ────────────────────────────────────────────────
  window.printFullReport = function() { window.print(); };

}());
</script>
</body>
</html>